/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\MyData\\Daily\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-a96c5e80",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a96c5e80").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-31e220a1",
    path: "/blogs/CSS/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31e220a1").then(next)
    },
  },
  {
    name: "v-3bd931fb",
    path: "/blogs/JavaScript/WebAPI.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bd931fb").then(next)
    },
  },
  {
    name: "v-bbb94484",
    path: "/blogs/C%E8%AF%AD%E8%A8%80/%E5%87%BD%E6%95%B0%E5%B0%8F%E8%AE%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bbb94484").then(next)
    },
  },
  {
    path: "/blogs/C语言/函数小记.html",
    redirect: "/blogs/C%E8%AF%AD%E8%A8%80/%E5%87%BD%E6%95%B0%E5%B0%8F%E8%AE%B0.html"
  },
  {
    path: "/blogs/C语言/函数小记.html",
    redirect: "/blogs/C%E8%AF%AD%E8%A8%80/%E5%87%BD%E6%95%B0%E5%B0%8F%E8%AE%B0.html"
  },
  {
    name: "v-a6bf4572",
    path: "/blogs/JavaScript/RegularExpression.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6bf4572").then(next)
    },
  },
  {
    name: "v-b3a5960a",
    path: "/blogs/JavaScript/jQuery.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3a5960a").then(next)
    },
  },
  {
    name: "v-26481be1",
    path: "/blogs/Vue/Vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26481be1").then(next)
    },
  },
  {
    name: "v-6e055221",
    path: "/blogs/other/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e055221").then(next)
    },
  },
  {
    name: "v-bc6631ca",
    path: "/blogs/vuepress/vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bc6631ca").then(next)
    },
  },
  {
    name: "v-34c608b2",
    path: "/blogs/%E5%90%8E%E7%AB%AF/MyBatis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34c608b2").then(next)
    },
  },
  {
    path: "/blogs/后端/MyBatis.html",
    redirect: "/blogs/%E5%90%8E%E7%AB%AF/MyBatis.html"
  },
  {
    path: "/blogs/后端/MyBatis.html",
    redirect: "/blogs/%E5%90%8E%E7%AB%AF/MyBatis.html"
  },
  {
    name: "v-dfa392ac",
    path: "/blogs/%E5%90%8E%E7%AB%AF/SpringBoot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dfa392ac").then(next)
    },
  },
  {
    path: "/blogs/后端/SpringBoot.html",
    redirect: "/blogs/%E5%90%8E%E7%AB%AF/SpringBoot.html"
  },
  {
    path: "/blogs/后端/SpringBoot.html",
    redirect: "/blogs/%E5%90%8E%E7%AB%AF/SpringBoot.html"
  },
  {
    name: "v-d1f4fd2c",
    path: "/blogs/%E5%90%8E%E7%AB%AF/Spring.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1f4fd2c").then(next)
    },
  },
  {
    path: "/blogs/后端/Spring.html",
    redirect: "/blogs/%E5%90%8E%E7%AB%AF/Spring.html"
  },
  {
    path: "/blogs/后端/Spring.html",
    redirect: "/blogs/%E5%90%8E%E7%AB%AF/Spring.html"
  },
  {
    name: "v-4b6b7dfe",
    path: "/blogs/%E5%90%8E%E7%AB%AF/SpringMVC.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b6b7dfe").then(next)
    },
  },
  {
    path: "/blogs/后端/SpringMVC.html",
    redirect: "/blogs/%E5%90%8E%E7%AB%AF/SpringMVC.html"
  },
  {
    path: "/blogs/后端/SpringMVC.html",
    redirect: "/blogs/%E5%90%8E%E7%AB%AF/SpringMVC.html"
  },
  {
    name: "v-1f9f56c9",
    path: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f9f56c9").then(next)
    },
  },
  {
    path: "/blogs/计算机基础/compositionPrinciple/",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/"
  },
  {
    path: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/index.html",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/"
  },
  {
    path: "/blogs/计算机基础/compositionPrinciple/",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/"
  },
  {
    name: "v-583e6a99",
    path: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-583e6a99").then(next)
    },
  },
  {
    path: "/blogs/计算机基础/computerNetwork/",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/"
  },
  {
    path: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/index.html",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/"
  },
  {
    path: "/blogs/计算机基础/computerNetwork/",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/"
  },
  {
    name: "v-575e9ced",
    path: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-575e9ced").then(next)
    },
  },
  {
    path: "/blogs/计算机基础/dataStructure/",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/"
  },
  {
    path: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/index.html",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/"
  },
  {
    path: "/blogs/计算机基础/dataStructure/",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/"
  },
  {
    name: "v-1b3db930",
    path: "/other/xiaoju.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b3db930").then(next)
    },
  },
  {
    name: "v-07ed4fc2",
    path: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07ed4fc2").then(next)
    },
  },
  {
    path: "/blogs/计算机基础/operatingSystem/",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/"
  },
  {
    path: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/index.html",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/"
  },
  {
    path: "/blogs/计算机基础/operatingSystem/",
    redirect: "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/"
  },
  {
    name: "v-1c254a3c",
    path: "/%E7%95%99%E8%A8%80%E6%9D%BF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c254a3c").then(next)
    },
  },
  {
    path: "/留言板.html",
    redirect: "/%E7%95%99%E8%A8%80%E6%9D%BF.html"
  },
  {
    path: "/留言板.html",
    redirect: "/%E7%95%99%E8%A8%80%E6%9D%BF.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-323b9794",
    path: "/tag/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-323b9794").then(next)
    },
    meta: {"pid":"tags","id":"css"}
  },
  {
    path: "/tag/css/index.html",
    redirect: "/tag/css/"
  },
  {
    name: "v-e8d965c8",
    path: "/tag/JS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d965c8").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/index.html",
    redirect: "/tag/JS/"
  },
  {
    name: "v-3258de12",
    path: "/tag/DOM/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3258de12").then(next)
    },
    meta: {"pid":"tags","id":"DOM"}
  },
  {
    path: "/tag/DOM/index.html",
    redirect: "/tag/DOM/"
  },
  {
    name: "v-325aaf8e",
    path: "/tag/BOM/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-325aaf8e").then(next)
    },
    meta: {"pid":"tags","id":"BOM"}
  },
  {
    path: "/tag/BOM/index.html",
    redirect: "/tag/BOM/"
  },
  {
    name: "v-eb5eaa9a",
    path: "/tag/C语言/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-eb5eaa9a").then(next)
    },
    meta: {"pid":"tags","id":"C语言"}
  },
  {
    path: "/tag/C语言/index.html",
    redirect: "/tag/C语言/"
  },
  {
    name: "v-89abd2d6",
    path: "/tag/算法/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-89abd2d6").then(next)
    },
    meta: {"pid":"tags","id":"算法"}
  },
  {
    path: "/tag/算法/index.html",
    redirect: "/tag/算法/"
  },
  {
    name: "v-5c9b2e55",
    path: "/tag/函数/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5c9b2e55").then(next)
    },
    meta: {"pid":"tags","id":"函数"}
  },
  {
    path: "/tag/函数/index.html",
    redirect: "/tag/函数/"
  },
  {
    name: "v-a4358e00",
    path: "/tag/正则表达式/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-a4358e00").then(next)
    },
    meta: {"pid":"tags","id":"正则表达式"}
  },
  {
    path: "/tag/正则表达式/index.html",
    redirect: "/tag/正则表达式/"
  },
  {
    name: "v-66172787",
    path: "/tag/jQuery/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-66172787").then(next)
    },
    meta: {"pid":"tags","id":"jQuery"}
  },
  {
    path: "/tag/jQuery/index.html",
    redirect: "/tag/jQuery/"
  },
  {
    name: "v-32475d9a",
    path: "/tag/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32475d9a").then(next)
    },
    meta: {"pid":"tags","id":"Vue"}
  },
  {
    path: "/tag/Vue/index.html",
    redirect: "/tag/Vue/"
  },
  {
    name: "v-1a384b6b",
    path: "/tag/框架/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1a384b6b").then(next)
    },
    meta: {"pid":"tags","id":"框架"}
  },
  {
    path: "/tag/框架/index.html",
    redirect: "/tag/框架/"
  },
  {
    name: "v-dfb71430",
    path: "/tag/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-dfb71430").then(next)
    },
    meta: {"pid":"tags","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/index.html",
    redirect: "/tag/vuepress/"
  },
  {
    name: "v-47997495",
    path: "/tag/后端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-47997495").then(next)
    },
    meta: {"pid":"tags","id":"后端"}
  },
  {
    path: "/tag/后端/index.html",
    redirect: "/tag/后端/"
  },
  {
    name: "v-f5f3b4b4",
    path: "/tag/MyBatis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-f5f3b4b4").then(next)
    },
    meta: {"pid":"tags","id":"MyBatis"}
  },
  {
    path: "/tag/MyBatis/index.html",
    redirect: "/tag/MyBatis/"
  },
  {
    name: "v-4bb4ec90",
    path: "/tag/Spring/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4bb4ec90").then(next)
    },
    meta: {"pid":"tags","id":"Spring"}
  },
  {
    path: "/tag/Spring/index.html",
    redirect: "/tag/Spring/"
  },
  {
    name: "v-54cc5f34",
    path: "/tag/SpringBoot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-54cc5f34").then(next)
    },
    meta: {"pid":"tags","id":"SpringBoot"}
  },
  {
    path: "/tag/SpringBoot/index.html",
    redirect: "/tag/SpringBoot/"
  },
  {
    name: "v-13372ce8",
    path: "/tag/SpringMVC/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-13372ce8").then(next)
    },
    meta: {"pid":"tags","id":"SpringMVC"}
  },
  {
    path: "/tag/SpringMVC/index.html",
    redirect: "/tag/SpringMVC/"
  },
  {
    name: "v-d4fd937a",
    path: "/tag/计算机基础/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d4fd937a").then(next)
    },
    meta: {"pid":"tags","id":"计算机基础"}
  },
  {
    path: "/tag/计算机基础/index.html",
    redirect: "/tag/计算机基础/"
  },
  {
    name: "v-4cb5e150",
    path: "/tag/计算机组成原理/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4cb5e150").then(next)
    },
    meta: {"pid":"tags","id":"计算机组成原理"}
  },
  {
    path: "/tag/计算机组成原理/index.html",
    redirect: "/tag/计算机组成原理/"
  },
  {
    name: "v-0aea8d27",
    path: "/tag/计算机网络/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0aea8d27").then(next)
    },
    meta: {"pid":"tags","id":"计算机网络"}
  },
  {
    path: "/tag/计算机网络/index.html",
    redirect: "/tag/计算机网络/"
  },
  {
    name: "v-92b3076c",
    path: "/tag/数据结构/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-92b3076c").then(next)
    },
    meta: {"pid":"tags","id":"数据结构"}
  },
  {
    path: "/tag/数据结构/index.html",
    redirect: "/tag/数据结构/"
  },
  {
    name: "v-9860895a",
    path: "/tag/操作系统/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-9860895a").then(next)
    },
    meta: {"pid":"tags","id":"操作系统"}
  },
  {
    path: "/tag/操作系统/index.html",
    redirect: "/tag/操作系统/"
  },
  {
    name: "v-7efe64ca",
    path: "/categories/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efe64ca").then(next)
    },
    meta: {"pid":"categories","id":"CSS"}
  },
  {
    path: "/categories/CSS/index.html",
    redirect: "/categories/CSS/"
  },
  {
    name: "v-081e6844",
    path: "/categories/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-081e6844").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/index.html",
    redirect: "/categories/JavaScript/"
  },
  {
    name: "v-22047b27",
    path: "/categories/C语言/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-22047b27").then(next)
    },
    meta: {"pid":"categories","id":"C语言"}
  },
  {
    path: "/categories/C语言/index.html",
    redirect: "/categories/C语言/"
  },
  {
    name: "v-7f0789a7",
    path: "/categories/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f0789a7").then(next)
    },
    meta: {"pid":"categories","id":"Vue"}
  },
  {
    path: "/categories/Vue/index.html",
    redirect: "/categories/Vue/"
  },
  {
    name: "v-9fa33418",
    path: "/categories/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-9fa33418").then(next)
    },
    meta: {"pid":"categories","id":"vuepress"}
  },
  {
    path: "/categories/vuepress/index.html",
    redirect: "/categories/vuepress/"
  },
  {
    name: "v-12afc5a1",
    path: "/categories/后端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-12afc5a1").then(next)
    },
    meta: {"pid":"categories","id":"后端"}
  },
  {
    path: "/categories/后端/index.html",
    redirect: "/categories/后端/"
  },
  {
    name: "v-0c66c492",
    path: "/categories/计算机基础/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-0c66c492").then(next)
    },
    meta: {"pid":"categories","id":"计算机基础"}
  },
  {
    path: "/categories/计算机基础/index.html",
    redirect: "/categories/计算机基础/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]