/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "小橘不颂兮",
  "description": "欢迎来到小橘不颂兮的个人博客",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "小橘不颂兮的个人博客，前端，计算机，摄影，学习，向前走吧"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "小橘不颂兮"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/icons/144.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/icons/144.png",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "https://at.alicdn.com/t/font_3211877_r75u9wkbvh.css",
        "type": "text/css"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "嗨！好久不见，记得要开心噢",
        "tagline": "小橘不颂兮",
        "bgImage": "/assets/img/bg/晚霞.jpg",
        "bgImageStyle": {
          "height": "450px"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "逝者如斯"
          },
          {
            "title": "Today",
            "details": "活于此刻"
          },
          {
            "title": "Tomorrow",
            "details": "孤独前行"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-a96c5e80",
      "path": "/",
      "lastUpdated": "2022/3/1 下午11:24:13",
      "lastUpdatedTimestamp": 1646148253000
    },
    {
      "title": "CSS学习笔记",
      "frontmatter": {
        "title": "CSS学习笔记",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "css"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/blogs/CSS/CSS.html",
      "relativePath": "blogs/CSS/CSS.md",
      "key": "v-31e220a1",
      "path": "/blogs/CSS/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "1.视口",
          "slug": "_1-视口"
        },
        {
          "level": 3,
          "title": "meta视口标签",
          "slug": "meta视口标签"
        },
        {
          "level": 3,
          "title": "标准的viewport设置",
          "slug": "标准的viewport设置"
        },
        {
          "level": 2,
          "title": "2.二倍图",
          "slug": "_2-二倍图"
        },
        {
          "level": 3,
          "title": "2.1\t物理像素&物理像素比",
          "slug": "_2-1物理像素-物理像素比"
        },
        {
          "level": 3,
          "title": "2.2\t多倍图",
          "slug": "_2-2多倍图"
        },
        {
          "level": 3,
          "title": "2.3\t背景缩放 background-size",
          "slug": "_2-3背景缩放-background-size"
        },
        {
          "level": 2,
          "title": "3.\t移动端技术解决方案",
          "slug": "_3-移动端技术解决方案"
        },
        {
          "level": 3,
          "title": "3.1\t移动端浏览器",
          "slug": "_3-1移动端浏览器"
        },
        {
          "level": 3,
          "title": "3.2\tCSS初始化 normalize.css",
          "slug": "_3-2css初始化-normalize-css"
        },
        {
          "level": 3,
          "title": "3.3\tCSS3 盒子模型 box-sizing",
          "slug": "_3-3css3-盒子模型-box-sizing"
        },
        {
          "level": 3,
          "title": "3.4\t特殊样式",
          "slug": "_3-4特殊样式"
        },
        {
          "level": 2,
          "title": "4.\t2D转换",
          "slug": "_4-2d转换"
        },
        {
          "level": 3,
          "title": "4.1\t2D转换之移动 translate",
          "slug": "_4-12d转换之移动-translate"
        },
        {
          "level": 3,
          "title": "4.2\t2D转换之旋转 rotate",
          "slug": "_4-22d转换之旋转-rotate"
        },
        {
          "level": 3,
          "title": "4.3\t2D转换中心点 transform-origin",
          "slug": "_4-32d转换中心点-transform-origin"
        },
        {
          "level": 3,
          "title": "4.4\t2D转换之缩放\t scale",
          "slug": "_4-42d转换之缩放-scale"
        },
        {
          "level": 2,
          "title": "5. \t动画",
          "slug": "_5-动画"
        },
        {
          "level": 3,
          "title": "简写属性",
          "slug": "简写属性"
        },
        {
          "level": 3,
          "title": "速度曲线细节",
          "slug": "速度曲线细节"
        },
        {
          "level": 2,
          "title": "6.\t3D转换",
          "slug": "_6-3d转换"
        },
        {
          "level": 3,
          "title": "透视",
          "slug": "透视"
        },
        {
          "level": 3,
          "title": "3D旋转\trotate3d",
          "slug": "_3d旋转rotate3d"
        },
        {
          "level": 3,
          "title": "3D呈现 transfrom-style",
          "slug": "_3d呈现-transfrom-style"
        },
        {
          "level": 2,
          "title": "移动web开发",
          "slug": "移动web开发"
        },
        {
          "level": 3,
          "title": "rem基础",
          "slug": "rem基础"
        },
        {
          "level": 3,
          "title": "媒体查询",
          "slug": "媒体查询"
        },
        {
          "level": 3,
          "title": "Less基础",
          "slug": "less基础"
        },
        {
          "level": 3,
          "title": "rem适配方案",
          "slug": "rem适配方案"
        },
        {
          "level": 2,
          "title": "Bootstarp使用",
          "slug": "bootstarp使用"
        },
        {
          "level": 3,
          "title": "布局容器",
          "slug": "布局容器"
        },
        {
          "level": 3,
          "title": "栅格布局",
          "slug": "栅格布局"
        },
        {
          "level": 3,
          "title": "响应式工具",
          "slug": "响应式工具"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "正则表达式",
      "frontmatter": {
        "title": "正则表达式",
        "date": "2021-10-28T00:00:00.000Z",
        "tags": [
          "JS",
          "正则表达式"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/RegularExpression.html",
      "relativePath": "blogs/JavaScript/RegularExpression.md",
      "key": "v-a6bf4572",
      "path": "/blogs/JavaScript/RegularExpression.html",
      "headers": [
        {
          "level": 2,
          "title": "基础",
          "slug": "基础"
        },
        {
          "level": 2,
          "title": "进阶",
          "slug": "进阶"
        },
        {
          "level": 3,
          "title": "分组",
          "slug": "分组"
        },
        {
          "level": 3,
          "title": "或者条件",
          "slug": "或者条件"
        },
        {
          "level": 3,
          "title": "非捕获分组",
          "slug": "非捕获分组"
        },
        {
          "level": 3,
          "title": "分组的回溯引用",
          "slug": "分组的回溯引用"
        },
        {
          "level": 2,
          "title": "规则",
          "slug": "规则"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "函数小记",
      "frontmatter": {
        "title": "函数小记",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "C语言",
          "算法",
          "函数"
        ],
        "categories": [
          "C语言"
        ]
      },
      "regularPath": "/blogs/C%E8%AF%AD%E8%A8%80/%E5%87%BD%E6%95%B0%E5%B0%8F%E8%AE%B0.html",
      "relativePath": "blogs/C语言/函数小记.md",
      "key": "v-bbb94484",
      "path": "/blogs/C%E8%AF%AD%E8%A8%80/%E5%87%BD%E6%95%B0%E5%B0%8F%E8%AE%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "函数篇",
          "slug": "函数篇"
        },
        {
          "level": 2,
          "title": "memcpy",
          "slug": "memcpy"
        },
        {
          "level": 2,
          "title": "sprintf",
          "slug": "sprintf"
        },
        {
          "level": 2,
          "title": "snprintf",
          "slug": "snprintf"
        },
        {
          "level": 2,
          "title": "qsort",
          "slug": "qsort"
        },
        {
          "level": 2,
          "title": "memset",
          "slug": "memset"
        },
        {
          "level": 2,
          "title": "strpbrk",
          "slug": "strpbrk"
        },
        {
          "level": 2,
          "title": "strtok",
          "slug": "strtok"
        },
        {
          "level": 2,
          "title": "calloc",
          "slug": "calloc"
        },
        {
          "level": 2,
          "title": "strcat",
          "slug": "strcat"
        },
        {
          "level": 2,
          "title": "isalpha",
          "slug": "isalpha"
        },
        {
          "level": 2,
          "title": "tolower",
          "slug": "tolower"
        },
        {
          "level": 2,
          "title": "strdup",
          "slug": "strdup"
        },
        {
          "level": 2,
          "title": "strndup",
          "slug": "strndup"
        },
        {
          "level": 2,
          "title": "assert",
          "slug": "assert"
        },
        {
          "level": 2,
          "title": "算法篇",
          "slug": "算法篇"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>随力扣刷题，所见函数，记录于此</p>\n</div>",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "jQuery",
      "frontmatter": {
        "title": "jQuery",
        "date": "2021-10-28T00:00:00.000Z",
        "tags": [
          "JS",
          "jQuery"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/jQuery.html",
      "relativePath": "blogs/JavaScript/jQuery.md",
      "key": "v-b3a5960a",
      "path": "/blogs/JavaScript/jQuery.html",
      "headers": [
        {
          "level": 2,
          "title": "概念",
          "slug": "概念"
        },
        {
          "level": 2,
          "title": "优点",
          "slug": "优点"
        },
        {
          "level": 2,
          "title": "入口函数",
          "slug": "入口函数"
        },
        {
          "level": 2,
          "title": "顶级对象\t\t$",
          "slug": "顶级对象"
        },
        {
          "level": 2,
          "title": "jQuery对象和DOM原生对象",
          "slug": "jquery对象和dom原生对象"
        },
        {
          "level": 3,
          "title": "jQuery对象和DOM原生对象相互转换",
          "slug": "jquery对象和dom原生对象相互转换"
        },
        {
          "level": 2,
          "title": "jQuery 选择器",
          "slug": "jquery-选择器"
        },
        {
          "level": 3,
          "title": "jQuery 基础选择器",
          "slug": "jquery-基础选择器"
        },
        {
          "level": 3,
          "title": "jQuery 层级选择器",
          "slug": "jquery-层级选择器"
        },
        {
          "level": 3,
          "title": "jQuery 筛选选择器",
          "slug": "jquery-筛选选择器"
        },
        {
          "level": 3,
          "title": "筛选方法",
          "slug": "筛选方法"
        },
        {
          "level": 3,
          "title": "隐式迭代",
          "slug": "隐式迭代"
        },
        {
          "level": 2,
          "title": "样式操作",
          "slug": "样式操作"
        },
        {
          "level": 3,
          "title": "操作CSS方法",
          "slug": "操作css方法"
        },
        {
          "level": 3,
          "title": "操作类方法",
          "slug": "操作类方法"
        },
        {
          "level": 3,
          "title": "类操作与className的区别",
          "slug": "类操作与classname的区别"
        },
        {
          "level": 2,
          "title": "jQuery效果",
          "slug": "jquery效果"
        },
        {
          "level": 3,
          "title": "显示隐藏效果",
          "slug": "显示隐藏效果"
        },
        {
          "level": 3,
          "title": "事件切换",
          "slug": "事件切换"
        },
        {
          "level": 3,
          "title": "淡入淡出效果",
          "slug": "淡入淡出效果"
        },
        {
          "level": 3,
          "title": "自定义动画animate",
          "slug": "自定义动画animate"
        },
        {
          "level": 2,
          "title": "jQuery属性操作",
          "slug": "jquery属性操作"
        },
        {
          "level": 3,
          "title": "设置固有属性值： prop()",
          "slug": "设置固有属性值-prop"
        },
        {
          "level": 3,
          "title": "设置或获取元素自定义属性值： attr()",
          "slug": "设置或获取元素自定义属性值-attr"
        },
        {
          "level": 2,
          "title": "jQuery元素操作",
          "slug": "jquery元素操作"
        },
        {
          "level": 3,
          "title": "遍历元素",
          "slug": "遍历元素"
        },
        {
          "level": 3,
          "title": "创建、添加、删除元素",
          "slug": "创建、添加、删除元素"
        },
        {
          "level": 2,
          "title": "jQuery事件",
          "slug": "jquery事件"
        },
        {
          "level": 3,
          "title": "事件绑定：on",
          "slug": "事件绑定-on"
        },
        {
          "level": 3,
          "title": "事件解绑：off()",
          "slug": "事件解绑-off"
        },
        {
          "level": 3,
          "title": "自动触发事件 : trigger()",
          "slug": "自动触发事件-trigger"
        },
        {
          "level": 2,
          "title": "事件对象",
          "slug": "事件对象"
        },
        {
          "level": 2,
          "title": "jQuery其他方法",
          "slug": "jquery其他方法"
        },
        {
          "level": 3,
          "title": "对象拷贝",
          "slug": "对象拷贝"
        },
        {
          "level": 3,
          "title": "多库共存",
          "slug": "多库共存"
        },
        {
          "level": 2,
          "title": "jQuery插件",
          "slug": "jquery插件"
        },
        {
          "level": 2,
          "title": "jQuery尺寸",
          "slug": "jquery尺寸"
        },
        {
          "level": 2,
          "title": "jQuery位置",
          "slug": "jquery位置"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "WebAPI",
      "frontmatter": {
        "title": "WebAPI",
        "date": "2021-10-28T00:00:00.000Z",
        "tags": [
          "JS",
          "DOM",
          "BOM"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/WebAPI.html",
      "relativePath": "blogs/JavaScript/WebAPI.md",
      "key": "v-3bd931fb",
      "path": "/blogs/JavaScript/WebAPI.html",
      "headers": [
        {
          "level": 2,
          "title": "1.事件",
          "slug": "_1-事件"
        },
        {
          "level": 2,
          "title": "三种创建元素的区别",
          "slug": "三种创建元素的区别"
        },
        {
          "level": 3,
          "title": "改",
          "slug": "改"
        },
        {
          "level": 3,
          "title": "查",
          "slug": "查"
        },
        {
          "level": 2,
          "title": "注册事件",
          "slug": "注册事件"
        },
        {
          "level": 3,
          "title": "DOM事件流",
          "slug": "dom事件流"
        },
        {
          "level": 3,
          "title": "事件对象常见的属性和方法",
          "slug": "事件对象常见的属性和方法"
        },
        {
          "level": 3,
          "title": "事件委托",
          "slug": "事件委托"
        },
        {
          "level": 3,
          "title": "鼠标事件",
          "slug": "鼠标事件"
        },
        {
          "level": 3,
          "title": "鼠标事件对象",
          "slug": "鼠标事件对象"
        },
        {
          "level": 3,
          "title": "键盘事件",
          "slug": "键盘事件"
        },
        {
          "level": 3,
          "title": "窗口加载事件",
          "slug": "窗口加载事件"
        },
        {
          "level": 3,
          "title": "调整窗口大小事件",
          "slug": "调整窗口大小事件"
        },
        {
          "level": 3,
          "title": "定时器",
          "slug": "定时器"
        },
        {
          "level": 2,
          "title": "同步和异步",
          "slug": "同步和异步"
        },
        {
          "level": 3,
          "title": "执行机制",
          "slug": "执行机制"
        },
        {
          "level": 3,
          "title": "location",
          "slug": "location"
        },
        {
          "level": 2,
          "title": "元素偏移",
          "slug": "元素偏移"
        },
        {
          "level": 3,
          "title": "offset",
          "slug": "offset"
        },
        {
          "level": 3,
          "title": "client",
          "slug": "client"
        },
        {
          "level": 3,
          "title": "scroll",
          "slug": "scroll"
        },
        {
          "level": 3,
          "title": "三大系列对比",
          "slug": "三大系列对比"
        },
        {
          "level": 3,
          "title": "mouseenter 和 mouseover的区别",
          "slug": "mouseenter-和-mouseover的区别"
        },
        {
          "level": 2,
          "title": "触屏事件",
          "slug": "触屏事件"
        },
        {
          "level": 3,
          "title": "触摸事件对象",
          "slug": "触摸事件对象"
        },
        {
          "level": 3,
          "title": "classList",
          "slug": "classlist"
        },
        {
          "level": 3,
          "title": "click事件延时问题解决",
          "slug": "click事件延时问题解决"
        },
        {
          "level": 2,
          "title": "本地存储",
          "slug": "本地存储"
        },
        {
          "level": 3,
          "title": "window.sessionStorage",
          "slug": "window-sessionstorage"
        },
        {
          "level": 3,
          "title": "window.localStorage",
          "slug": "window-localstorage"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>有关js原生DOM和BOM的知识点</p>\n</div>",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "Vue2.x学习笔记",
      "frontmatter": {
        "title": "Vue2.x学习笔记",
        "date": "2022-2-28",
        "tags": [
          "Vue",
          "框架"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/Vue/Vue.html",
      "relativePath": "blogs/Vue/Vue.md",
      "key": "v-26481be1",
      "path": "/blogs/Vue/Vue.html",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "vuepress-theme-reco",
      "frontmatter": {
        "title": "vuepress-theme-reco",
        "date": "2019-04-09T00:00:00.000Z"
      },
      "regularPath": "/blogs/other/guide.html",
      "relativePath": "blogs/other/guide.md",
      "key": "v-6e055221",
      "path": "/blogs/other/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Use",
          "slug": "use"
        },
        {
          "level": 2,
          "title": "Play Together",
          "slug": "play-together"
        },
        {
          "level": 3,
          "title": "0.x",
          "slug": "_0-x"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 3,
          "title": "CLI",
          "slug": "cli"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "MyBatis",
      "frontmatter": {
        "title": "MyBatis",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "后端",
          "MyBatis",
          "框架"
        ],
        "categories": [
          "后端"
        ]
      },
      "regularPath": "/blogs/%E5%90%8E%E7%AB%AF/MyBatis.html",
      "relativePath": "blogs/后端/MyBatis.md",
      "key": "v-34c608b2",
      "path": "/blogs/%E5%90%8E%E7%AB%AF/MyBatis.html",
      "headers": [
        {
          "level": 2,
          "title": "1、概述",
          "slug": "_1、概述"
        },
        {
          "level": 3,
          "title": "1.1、持久化",
          "slug": "_1-1、持久化"
        },
        {
          "level": 3,
          "title": "1.2、持久层",
          "slug": "_1-2、持久层"
        },
        {
          "level": 3,
          "title": "1.3、MyBatis的用处",
          "slug": "_1-3、mybatis的用处"
        },
        {
          "level": 2,
          "title": "2、Mybatis程序",
          "slug": "_2、mybatis程序"
        },
        {
          "level": 3,
          "title": "2.1、搭建环境",
          "slug": "_2-1、搭建环境"
        },
        {
          "level": 3,
          "title": "2.2、编写代码",
          "slug": "_2-2、编写代码"
        },
        {
          "level": 3,
          "title": "2.3、测试",
          "slug": "_2-3、测试"
        },
        {
          "level": 2,
          "title": "3、CRUD",
          "slug": "_3、crud"
        },
        {
          "level": 3,
          "title": "1.xml文件中：",
          "slug": "_1-xml文件中"
        },
        {
          "level": 2,
          "title": "4、配置解析",
          "slug": "_4、配置解析"
        },
        {
          "level": 3,
          "title": "1、核心配置文件",
          "slug": "_1、核心配置文件"
        },
        {
          "level": 3,
          "title": "2、环境配置（environments）",
          "slug": "_2、环境配置-environments"
        },
        {
          "level": 3,
          "title": "3、属性（properties）",
          "slug": "_3、属性-properties"
        },
        {
          "level": 3,
          "title": "4、类型别名（typeAliases）",
          "slug": "_4、类型别名-typealiases"
        },
        {
          "level": 3,
          "title": "5、设置",
          "slug": "_5、设置"
        },
        {
          "level": 3,
          "title": "6、其他设置",
          "slug": "_6、其他设置"
        },
        {
          "level": 3,
          "title": "7、映射器（mappers）",
          "slug": "_7、映射器-mappers"
        },
        {
          "level": 3,
          "title": "8、生命周期和作用域",
          "slug": "_8、生命周期和作用域"
        },
        {
          "level": 2,
          "title": "5、解决属性名和字段名不一致的问题",
          "slug": "_5、解决属性名和字段名不一致的问题"
        },
        {
          "level": 2,
          "title": "6、日志",
          "slug": "_6、日志"
        },
        {
          "level": 3,
          "title": "6.1、日志工厂",
          "slug": "_6-1、日志工厂"
        },
        {
          "level": 3,
          "title": "6.2、Log4j",
          "slug": "_6-2、log4j"
        },
        {
          "level": 2,
          "title": "7、分页",
          "slug": "_7、分页"
        },
        {
          "level": 2,
          "title": "8、注解开发",
          "slug": "_8、注解开发"
        },
        {
          "level": 3,
          "title": "8.1、面向接口编程",
          "slug": "_8-1、面向接口编程"
        },
        {
          "level": 3,
          "title": "8.2、使用注解开发",
          "slug": "_8-2、使用注解开发"
        },
        {
          "level": 3,
          "title": "8.3、CRUD",
          "slug": "_8-3、crud"
        },
        {
          "level": 2,
          "title": "9、动态SQL",
          "slug": "_9、动态sql"
        },
        {
          "level": 3,
          "title": "IF",
          "slug": "if"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "SpringBoot",
      "frontmatter": {
        "title": "SpringBoot",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "后端",
          "Spring",
          "SpringBoot",
          "框架"
        ],
        "categories": [
          "后端"
        ]
      },
      "regularPath": "/blogs/%E5%90%8E%E7%AB%AF/SpringBoot.html",
      "relativePath": "blogs/后端/SpringBoot.md",
      "key": "v-dfa392ac",
      "path": "/blogs/%E5%90%8E%E7%AB%AF/SpringBoot.html",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "vuepress构建步骤",
      "frontmatter": {
        "title": "vuepress构建步骤",
        "date": "2022-3-1",
        "sticky": 1,
        "tags": [
          "vuepress"
        ],
        "categories": [
          "vuepress"
        ]
      },
      "regularPath": "/blogs/vuepress/vuepress.html",
      "relativePath": "blogs/vuepress/vuepress.md",
      "key": "v-bc6631ca",
      "path": "/blogs/vuepress/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "准备工作",
          "slug": "准备工作"
        },
        {
          "level": 2,
          "title": "在github中新建项目",
          "slug": "在github中新建项目"
        },
        {
          "level": 2,
          "title": "构建项目",
          "slug": "构建项目"
        },
        {
          "level": 2,
          "title": "基本配置",
          "slug": "基本配置"
        },
        {
          "level": 3,
          "title": "配置config.js",
          "slug": "配置config-js"
        },
        {
          "level": 3,
          "title": "配置导航栏以及侧边栏",
          "slug": "配置导航栏以及侧边栏"
        },
        {
          "level": 2,
          "title": "更新时间",
          "slug": "更新时间"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用-2"
        },
        {
          "level": 3,
          "title": "选项",
          "slug": "选项"
        },
        {
          "level": 2,
          "title": "发布",
          "slug": "发布"
        },
        {
          "level": 3,
          "title": "创建deploy.sh",
          "slug": "创建deploy-sh"
        },
        {
          "level": 3,
          "title": "Github Pages部署",
          "slug": "github-pages部署"
        },
        {
          "level": 2,
          "title": "配置PWA",
          "slug": "配置pwa"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装-2"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用-3"
        },
        {
          "level": 2,
          "title": "vssue评论",
          "slug": "vssue评论"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装-3"
        },
        {
          "level": 3,
          "title": "使用插件",
          "slug": "使用插件"
        },
        {
          "level": 3,
          "title": "clientId和clientSecret 生成",
          "slug": "clientid和clientsecret-生成"
        },
        {
          "level": 3,
          "title": "使用 Vssue 组件",
          "slug": "使用-vssue-组件"
        },
        {
          "level": 3,
          "title": "全局配置Vssue",
          "slug": "全局配置vssue"
        },
        {
          "level": 2,
          "title": "back-to-top",
          "slug": "back-to-top"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装-4"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用-4"
        },
        {
          "level": 2,
          "title": "图片缩放",
          "slug": "图片缩放"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装-5"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用-5"
        },
        {
          "level": 2,
          "title": "Github Actions自动部署",
          "slug": "github-actions自动部署"
        },
        {
          "level": 3,
          "title": "创建deploy.yml",
          "slug": "创建deploy-yml"
        },
        {
          "level": 3,
          "title": "生成令牌",
          "slug": "生成令牌"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>想搭建一个属于自己的博客吗？这里应该有你需要的</p>\n</div>",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "计算机组成原理",
      "frontmatter": {
        "title": "计算机组成原理",
        "date": "2022-2-28",
        "sidebar": "auto",
        "tags": [
          "计算机基础",
          "计算机组成原理"
        ],
        "categories": [
          "计算机基础"
        ]
      },
      "regularPath": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/",
      "relativePath": "blogs/计算机基础/compositionPrinciple/README.md",
      "key": "v-1f9f56c9",
      "path": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "计算机网络",
      "frontmatter": {
        "title": "计算机网络",
        "date": "2022-2-28",
        "sidebar": "auto",
        "tags": [
          "计算机基础",
          "计算机网络"
        ],
        "categories": [
          "计算机基础"
        ]
      },
      "regularPath": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/",
      "relativePath": "blogs/计算机基础/computerNetwork/README.md",
      "key": "v-583e6a99",
      "path": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/",
      "headers": [
        {
          "level": 2,
          "title": "第一章、概述",
          "slug": "第一章、概述"
        },
        {
          "level": 3,
          "title": "概念、功能、组成、分类",
          "slug": "概念、功能、组成、分类"
        },
        {
          "level": 3,
          "title": "性能指标",
          "slug": "性能指标"
        },
        {
          "level": 3,
          "title": "计算机网络体系结构",
          "slug": "计算机网络体系结构"
        },
        {
          "level": 2,
          "title": "第二章、物理层",
          "slug": "第二章、物理层"
        },
        {
          "level": 3,
          "title": "数据通信的基础知识",
          "slug": "数据通信的基础知识"
        },
        {
          "level": 3,
          "title": "导向性传输介质",
          "slug": "导向性传输介质"
        },
        {
          "level": 3,
          "title": "非导向性传输介质",
          "slug": "非导向性传输介质"
        },
        {
          "level": 3,
          "title": "中继器",
          "slug": "中继器"
        },
        {
          "level": 3,
          "title": "5-4-3规则。",
          "slug": "_5-4-3规则。"
        },
        {
          "level": 2,
          "title": "第三章、数据链路层",
          "slug": "第三章、数据链路层"
        },
        {
          "level": 3,
          "title": "基本概念",
          "slug": "基本概念"
        },
        {
          "level": 3,
          "title": "组帧",
          "slug": "组帧"
        },
        {
          "level": 3,
          "title": "差错",
          "slug": "差错"
        },
        {
          "level": 3,
          "title": "流量控制和可靠传输机制",
          "slug": "流量控制和可靠传输机制"
        },
        {
          "level": 3,
          "title": "介质访问控制",
          "slug": "介质访问控制"
        },
        {
          "level": 3,
          "title": "局域网",
          "slug": "局域网"
        },
        {
          "level": 3,
          "title": "广域网",
          "slug": "广域网"
        },
        {
          "level": 3,
          "title": "链路层设备",
          "slug": "链路层设备"
        },
        {
          "level": 2,
          "title": "第四章、网络层",
          "slug": "第四章、网络层"
        },
        {
          "level": 3,
          "title": "数据交换方式",
          "slug": "数据交换方式"
        },
        {
          "level": 3,
          "title": "网际协议IP",
          "slug": "网际协议ip"
        },
        {
          "level": 3,
          "title": "网际控制报文协议ICMP",
          "slug": "网际控制报文协议icmp"
        },
        {
          "level": 3,
          "title": "IPv6",
          "slug": "ipv6"
        },
        {
          "level": 3,
          "title": "路由选择协议",
          "slug": "路由选择协议"
        },
        {
          "level": 3,
          "title": "IP多播",
          "slug": "ip多播"
        },
        {
          "level": 3,
          "title": "移动IP",
          "slug": "移动ip"
        },
        {
          "level": 3,
          "title": "网络层设备",
          "slug": "网络层设备"
        },
        {
          "level": 2,
          "title": "第五章、运输层",
          "slug": "第五章、运输层"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 3,
          "title": "UDP协议",
          "slug": "udp协议"
        },
        {
          "level": 3,
          "title": "TCP协议",
          "slug": "tcp协议"
        },
        {
          "level": 2,
          "title": "第六章、应用层",
          "slug": "第六章、应用层"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "Spring",
      "frontmatter": {
        "title": "Spring",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "后端",
          "Spring",
          "框架"
        ],
        "categories": [
          "后端"
        ]
      },
      "regularPath": "/blogs/%E5%90%8E%E7%AB%AF/Spring.html",
      "relativePath": "blogs/后端/Spring.md",
      "key": "v-d1f4fd2c",
      "path": "/blogs/%E5%90%8E%E7%AB%AF/Spring.html",
      "headers": [
        {
          "level": 2,
          "title": "1、Spring创建",
          "slug": "_1、spring创建"
        },
        {
          "level": 2,
          "title": "2、项目基础",
          "slug": "_2、项目基础"
        },
        {
          "level": 3,
          "title": "自动注解",
          "slug": "自动注解"
        },
        {
          "level": 3,
          "title": "多配置文件",
          "slug": "多配置文件"
        },
        {
          "level": 3,
          "title": "注解",
          "slug": "注解"
        },
        {
          "level": 2,
          "title": "3、动态代理",
          "slug": "_3、动态代理"
        },
        {
          "level": 3,
          "title": "动态代理的作用",
          "slug": "动态代理的作用"
        },
        {
          "level": 3,
          "title": "Aop（Aspect Oriented Programming）",
          "slug": "aop-aspect-oriented-programming"
        },
        {
          "level": 3,
          "title": "aop的实现",
          "slug": "aop的实现"
        },
        {
          "level": 3,
          "title": "JoinPoint",
          "slug": "joinpoint"
        },
        {
          "level": 2,
          "title": "4、spring和mybatis",
          "slug": "_4、spring和mybatis"
        },
        {
          "level": 3,
          "title": "mybatis使用",
          "slug": "mybatis使用"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 2,
          "title": "5、spring事务",
          "slug": "_5、spring事务"
        },
        {
          "level": 3,
          "title": "步骤",
          "slug": "步骤"
        },
        {
          "level": 3,
          "title": "使用spring事务注解管理事务",
          "slug": "使用spring事务注解管理事务"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "数据结构",
      "frontmatter": {
        "title": "数据结构",
        "date": "2022-2-28",
        "sidebar": "auto",
        "tags": [
          "计算机基础",
          "数据结构"
        ],
        "categories": [
          "计算机基础"
        ]
      },
      "regularPath": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/",
      "relativePath": "blogs/计算机基础/dataStructure/README.md",
      "key": "v-575e9ced",
      "path": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/",
      "headers": [
        {
          "level": 2,
          "title": "绪论",
          "slug": "绪论"
        },
        {
          "level": 2,
          "title": "线性表",
          "slug": "线性表"
        },
        {
          "level": 3,
          "title": "顺序表",
          "slug": "顺序表"
        },
        {
          "level": 3,
          "title": "链表",
          "slug": "链表"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "操作系统",
      "frontmatter": {
        "title": "操作系统",
        "date": "2022-2-28",
        "sidebar": "auto",
        "tags": [
          "计算机基础",
          "操作系统"
        ],
        "categories": [
          "计算机基础"
        ]
      },
      "regularPath": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/",
      "relativePath": "blogs/计算机基础/operatingSystem/README.md",
      "key": "v-07ed4fc2",
      "path": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "SpringMVC",
      "frontmatter": {
        "title": "SpringMVC",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "后端",
          "Spring",
          "SpringMVC",
          "框架"
        ],
        "categories": [
          "后端"
        ]
      },
      "regularPath": "/blogs/%E5%90%8E%E7%AB%AF/SpringMVC.html",
      "relativePath": "blogs/后端/SpringMVC.md",
      "key": "v-4b6b7dfe",
      "path": "/blogs/%E5%90%8E%E7%AB%AF/SpringMVC.html",
      "headers": [
        {
          "level": 2,
          "title": "1、创建项目",
          "slug": "_1、创建项目"
        },
        {
          "level": 3,
          "title": "实现步骤",
          "slug": "实现步骤"
        },
        {
          "level": 3,
          "title": "springmvc请求的处理流程",
          "slug": "springmvc请求的处理流程"
        },
        {
          "level": 3,
          "title": "springmvc执行过程源代码分析",
          "slug": "springmvc执行过程源代码分析"
        },
        {
          "level": 2,
          "title": "2、注解",
          "slug": "_2、注解"
        },
        {
          "level": 3,
          "title": "@RequestMapping",
          "slug": "requestmapping"
        },
        {
          "level": 3,
          "title": "@RequestParam",
          "slug": "requestparam"
        },
        {
          "level": 3,
          "title": "@ResponseBody",
          "slug": "responsebody"
        },
        {
          "level": 2,
          "title": "地址分类：",
          "slug": "地址分类"
        },
        {
          "level": 2,
          "title": "SSM",
          "slug": "ssm"
        },
        {
          "level": 3,
          "title": "步骤：",
          "slug": "步骤"
        },
        {
          "level": 2,
          "title": "异常处理",
          "slug": "异常处理"
        },
        {
          "level": 2,
          "title": "拦截器",
          "slug": "拦截器"
        }
      ],
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我",
        "date": "2022-3-1",
        "subSidebar": false,
        "keys": [
          "2d7cd5c74163fa45b5d7bdb458b7a5e4"
        ]
      },
      "regularPath": "/other/xiaoju.html",
      "relativePath": "other/xiaoju.md",
      "key": "v-1b3db930",
      "path": "/other/xiaoju.html",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    },
    {
      "title": "留言板",
      "frontmatter": {
        "title": "留言板",
        "date": "2022-2-28",
        "subSidebar": false
      },
      "regularPath": "/%E7%95%99%E8%A8%80%E6%9D%BF.html",
      "relativePath": "留言板.md",
      "key": "v-1c254a3c",
      "path": "/%E7%95%99%E8%A8%80%E6%9D%BF.html",
      "lastUpdated": "2022/3/1 下午9:56:05",
      "lastUpdatedTimestamp": 1646142965000
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "工具箱",
        "icon": "iconfont icon-gongju",
        "items": [
          {
            "text": "兼容性查询（前端必备）",
            "link": "https://caniuse.com"
          },
          {
            "text": "API请求测试",
            "link": "https://httpbin.org/"
          },
          {
            "text": "在线PS",
            "link": "https://ps.gaoding.com/#/"
          },
          {
            "text": "在线一键抠图",
            "link": "https://www.remove.bg/zh"
          },
          {
            "text": "API请求测试",
            "link": "https://snippet-generator.app/"
          },
          {
            "text": "Lks推荐网站合集（实用）",
            "link": "https://xiangjianan.gitee.io/lks/"
          },
          {
            "text": "壁纸站",
            "link": "https://wallhaven.cc/"
          },
          {
            "text": "CSS渐变色",
            "link": "https://color.oulu.me/"
          },
          {
            "text": "前端样式平台",
            "link": "https://codepen.io/?cursor=ZD0xJm89MCZwPTEmdj02Njc4OA=="
          },
          {
            "text": "在线JSON校验",
            "link": "https://www.bejson.com/"
          },
          {
            "text": "格式转换工具——convertio",
            "link": "https://convertio.co/zh/"
          },
          {
            "text": "格式转换工具——aconvert",
            "link": "https://www.aconvert.com/cn/"
          },
          {
            "text": "中国传统颜色",
            "link": "http://zhongguose.com/"
          },
          {
            "text": "千亿像素看中国",
            "link": "http://www.bigpixel.cn/"
          },
          {
            "text": "文档搜索引擎",
            "link": "https://www.jiumodiary.com/"
          },
          {
            "text": "在线字体（前端可用）",
            "link": "https://www.webfont.com/"
          },
          {
            "text": "艺术字体库",
            "link": "http://www.diyiziti.com/"
          }
        ]
      },
      {
        "text": "留言板",
        "icon": "reco-message",
        "link": "/留言板"
      },
      {
        "text": "关于",
        "icon": "reco-message",
        "items": [
          {
            "text": "关于我",
            "link": "/other/xiaoju",
            "icon": "reco-account"
          },
          {
            "text": "GitHub",
            "link": "https://github.com/recoluan",
            "icon": "reco-github"
          },
          {
            "text": "CSDN",
            "link": "https://www.csdn.net/",
            "icon": "reco-csdn"
          },
          {
            "text": "LeanCloud",
            "link": "https://console.leancloud.cn/apps",
            "icon": "iconfont icon-gongju"
          }
        ]
      }
    ],
    "valineConfig": {
      "appId": "DXFkz6H4Ht7b9lXaJfBdR5sv-gzGzoHsz",
      "appKey": "5hqYKCfaazHurBbjUU2sAP1Y"
    },
    "subSidebar": "auto",
    "sidebar": {
      "/blogs/计算机基础/": [
        "compositionPrinciple/",
        "computerNetwork/",
        "dataStructure/",
        "operatingSystem/"
      ],
      "/blogs/CSS/": [
        "CSS"
      ],
      "/blogs/JavaScript/": [
        "jQuery",
        "RegularExpression",
        "WebAPI"
      ],
      "/blogs/Vue/": [
        "Vue"
      ],
      "/blogs/后端/": [
        "MyBatis",
        "Spring",
        "SpringBoot",
        "SpringMVC"
      ],
      "/blogs/vuepress/": [
        "vuepress"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.（主题的作者大佬）",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      }
    ],
    "logo": "/小橘.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "更新时间",
    "author": "小橘",
    "authorAvatar": "/assets/img/avatar/mmexport1639710400520.jpg",
    "record": "xxxx",
    "startYear": "2022 "
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}