/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "小橘不颂兮",
  "description": "欢迎来到小橘不颂兮的个人博客",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "小橘不颂兮的个人博客，前端，计算机，摄影，学习，向前走吧"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "小橘不颂兮"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/icons/144.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/icons/144.png",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "https://at.alicdn.com/t/font_3211877_r75u9wkbvh.css",
        "type": "text/css"
      }
    ]
  ],
  "pages": [
    {
      "title": "SpringBoot",
      "frontmatter": {
        "title": "SpringBoot",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "后端",
          "Spring",
          "SpringBoot",
          "框架"
        ],
        "categories": [
          "后端"
        ]
      },
      "regularPath": "/blogs/%E5%90%8E%E7%AB%AF/SpringBoot.html",
      "relativePath": "blogs/后端/SpringBoot.md",
      "key": "v-dfa392ac",
      "path": "/blogs/%E5%90%8E%E7%AB%AF/SpringBoot.html"
    },
    {
      "title": "MyBatis",
      "frontmatter": {
        "title": "MyBatis",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "后端",
          "MyBatis",
          "框架"
        ],
        "categories": [
          "后端"
        ]
      },
      "regularPath": "/blogs/%E5%90%8E%E7%AB%AF/MyBatis.html",
      "relativePath": "blogs/后端/MyBatis.md",
      "key": "v-34c608b2",
      "path": "/blogs/%E5%90%8E%E7%AB%AF/MyBatis.html",
      "headers": [
        {
          "level": 2,
          "title": "1、概述",
          "slug": "_1、概述"
        },
        {
          "level": 3,
          "title": "1.1、持久化",
          "slug": "_1-1、持久化"
        },
        {
          "level": 3,
          "title": "1.2、持久层",
          "slug": "_1-2、持久层"
        },
        {
          "level": 3,
          "title": "1.3、MyBatis的用处",
          "slug": "_1-3、mybatis的用处"
        },
        {
          "level": 2,
          "title": "2、Mybatis程序",
          "slug": "_2、mybatis程序"
        },
        {
          "level": 3,
          "title": "2.1、搭建环境",
          "slug": "_2-1、搭建环境"
        },
        {
          "level": 3,
          "title": "2.2、编写代码",
          "slug": "_2-2、编写代码"
        },
        {
          "level": 3,
          "title": "2.3、测试",
          "slug": "_2-3、测试"
        },
        {
          "level": 2,
          "title": "3、CRUD",
          "slug": "_3、crud"
        },
        {
          "level": 3,
          "title": "1.xml文件中：",
          "slug": "_1-xml文件中"
        },
        {
          "level": 2,
          "title": "4、配置解析",
          "slug": "_4、配置解析"
        },
        {
          "level": 3,
          "title": "1、核心配置文件",
          "slug": "_1、核心配置文件"
        },
        {
          "level": 3,
          "title": "2、环境配置（environments）",
          "slug": "_2、环境配置-environments"
        },
        {
          "level": 3,
          "title": "3、属性（properties）",
          "slug": "_3、属性-properties"
        },
        {
          "level": 3,
          "title": "4、类型别名（typeAliases）",
          "slug": "_4、类型别名-typealiases"
        },
        {
          "level": 3,
          "title": "5、设置",
          "slug": "_5、设置"
        },
        {
          "level": 3,
          "title": "6、其他设置",
          "slug": "_6、其他设置"
        },
        {
          "level": 3,
          "title": "7、映射器（mappers）",
          "slug": "_7、映射器-mappers"
        },
        {
          "level": 3,
          "title": "8、生命周期和作用域",
          "slug": "_8、生命周期和作用域"
        },
        {
          "level": 2,
          "title": "5、解决属性名和字段名不一致的问题",
          "slug": "_5、解决属性名和字段名不一致的问题"
        },
        {
          "level": 2,
          "title": "6、日志",
          "slug": "_6、日志"
        },
        {
          "level": 3,
          "title": "6.1、日志工厂",
          "slug": "_6-1、日志工厂"
        },
        {
          "level": 3,
          "title": "6.2、Log4j",
          "slug": "_6-2、log4j"
        },
        {
          "level": 2,
          "title": "7、分页",
          "slug": "_7、分页"
        },
        {
          "level": 2,
          "title": "8、注解开发",
          "slug": "_8、注解开发"
        },
        {
          "level": 3,
          "title": "8.1、面向接口编程",
          "slug": "_8-1、面向接口编程"
        },
        {
          "level": 3,
          "title": "8.2、使用注解开发",
          "slug": "_8-2、使用注解开发"
        },
        {
          "level": 3,
          "title": "8.3、CRUD",
          "slug": "_8-3、crud"
        },
        {
          "level": 2,
          "title": "9、动态SQL",
          "slug": "_9、动态sql"
        },
        {
          "level": 3,
          "title": "IF",
          "slug": "if"
        }
      ]
    },
    {
      "title": "SpringMVC",
      "frontmatter": {
        "title": "SpringMVC",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "后端",
          "Spring",
          "SpringMVC",
          "框架"
        ],
        "categories": [
          "后端"
        ]
      },
      "regularPath": "/blogs/%E5%90%8E%E7%AB%AF/SpringMVC.html",
      "relativePath": "blogs/后端/SpringMVC.md",
      "key": "v-4b6b7dfe",
      "path": "/blogs/%E5%90%8E%E7%AB%AF/SpringMVC.html",
      "headers": [
        {
          "level": 2,
          "title": "1、创建项目",
          "slug": "_1、创建项目"
        },
        {
          "level": 3,
          "title": "实现步骤",
          "slug": "实现步骤"
        },
        {
          "level": 3,
          "title": "springmvc请求的处理流程",
          "slug": "springmvc请求的处理流程"
        },
        {
          "level": 3,
          "title": "springmvc执行过程源代码分析",
          "slug": "springmvc执行过程源代码分析"
        },
        {
          "level": 2,
          "title": "2、注解",
          "slug": "_2、注解"
        },
        {
          "level": 3,
          "title": "@RequestMapping",
          "slug": "requestmapping"
        },
        {
          "level": 3,
          "title": "@RequestParam",
          "slug": "requestparam"
        },
        {
          "level": 3,
          "title": "@ResponseBody",
          "slug": "responsebody"
        },
        {
          "level": 2,
          "title": "地址分类：",
          "slug": "地址分类"
        },
        {
          "level": 2,
          "title": "SSM",
          "slug": "ssm"
        },
        {
          "level": 3,
          "title": "步骤：",
          "slug": "步骤"
        },
        {
          "level": 2,
          "title": "异常处理",
          "slug": "异常处理"
        },
        {
          "level": 2,
          "title": "拦截器",
          "slug": "拦截器"
        }
      ]
    },
    {
      "title": "算法学习记录",
      "frontmatter": {
        "title": "算法学习记录",
        "date": "2022-3-2",
        "tags": [
          "算法",
          "C语言",
          "数据结构"
        ],
        "categories": [
          "算法"
        ]
      },
      "regularPath": "/blogs/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.html",
      "relativePath": "blogs/算法/算法学习记录.md",
      "key": "v-9c20d530",
      "path": "/blogs/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.html",
      "headers": [
        {
          "level": 2,
          "title": "Morris 遍历",
          "slug": "morris-遍历"
        },
        {
          "level": 3,
          "title": "前序遍历二叉树",
          "slug": "前序遍历二叉树"
        },
        {
          "level": 3,
          "title": "中序遍历二叉树",
          "slug": "中序遍历二叉树"
        }
      ]
    },
    {
      "title": "计算机组成原理",
      "frontmatter": {
        "title": "计算机组成原理",
        "date": "2022-2-28",
        "sidebar": "auto",
        "tags": [
          "计算机基础",
          "计算机组成原理"
        ],
        "categories": [
          "计算机基础"
        ]
      },
      "regularPath": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/",
      "relativePath": "blogs/计算机基础/compositionPrinciple/README.md",
      "key": "v-1f9f56c9",
      "path": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/compositionPrinciple/"
    },
    {
      "title": "数据结构",
      "frontmatter": {
        "title": "数据结构",
        "date": "2022-2-28",
        "sidebar": "auto",
        "tags": [
          "计算机基础",
          "数据结构"
        ],
        "categories": [
          "计算机基础"
        ]
      },
      "regularPath": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/",
      "relativePath": "blogs/计算机基础/dataStructure/README.md",
      "key": "v-575e9ced",
      "path": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/dataStructure/",
      "headers": [
        {
          "level": 2,
          "title": "绪论",
          "slug": "绪论"
        },
        {
          "level": 2,
          "title": "线性表",
          "slug": "线性表"
        },
        {
          "level": 3,
          "title": "顺序表",
          "slug": "顺序表"
        },
        {
          "level": 3,
          "title": "链表",
          "slug": "链表"
        },
        {
          "level": 2,
          "title": "图",
          "slug": "图"
        }
      ]
    },
    {
      "title": "计算机网络",
      "frontmatter": {
        "title": "计算机网络",
        "date": "2022-2-28",
        "sidebar": "auto",
        "tags": [
          "计算机基础",
          "计算机网络"
        ],
        "categories": [
          "计算机基础"
        ]
      },
      "regularPath": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/",
      "relativePath": "blogs/计算机基础/computerNetwork/README.md",
      "key": "v-583e6a99",
      "path": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/computerNetwork/",
      "headers": [
        {
          "level": 2,
          "title": "第一章、概述",
          "slug": "第一章、概述"
        },
        {
          "level": 3,
          "title": "概念、功能、组成、分类",
          "slug": "概念、功能、组成、分类"
        },
        {
          "level": 3,
          "title": "性能指标",
          "slug": "性能指标"
        },
        {
          "level": 3,
          "title": "计算机网络体系结构",
          "slug": "计算机网络体系结构"
        },
        {
          "level": 2,
          "title": "第二章、物理层",
          "slug": "第二章、物理层"
        },
        {
          "level": 3,
          "title": "数据通信的基础知识",
          "slug": "数据通信的基础知识"
        },
        {
          "level": 3,
          "title": "导向性传输介质",
          "slug": "导向性传输介质"
        },
        {
          "level": 3,
          "title": "非导向性传输介质",
          "slug": "非导向性传输介质"
        },
        {
          "level": 3,
          "title": "中继器",
          "slug": "中继器"
        },
        {
          "level": 3,
          "title": "5-4-3规则。",
          "slug": "_5-4-3规则。"
        },
        {
          "level": 2,
          "title": "第三章、数据链路层",
          "slug": "第三章、数据链路层"
        },
        {
          "level": 3,
          "title": "基本概念",
          "slug": "基本概念"
        },
        {
          "level": 3,
          "title": "组帧",
          "slug": "组帧"
        },
        {
          "level": 3,
          "title": "差错",
          "slug": "差错"
        },
        {
          "level": 3,
          "title": "流量控制和可靠传输机制",
          "slug": "流量控制和可靠传输机制"
        },
        {
          "level": 3,
          "title": "介质访问控制",
          "slug": "介质访问控制"
        },
        {
          "level": 3,
          "title": "局域网",
          "slug": "局域网"
        },
        {
          "level": 3,
          "title": "广域网",
          "slug": "广域网"
        },
        {
          "level": 3,
          "title": "链路层设备",
          "slug": "链路层设备"
        },
        {
          "level": 2,
          "title": "第四章、网络层",
          "slug": "第四章、网络层"
        },
        {
          "level": 3,
          "title": "数据交换方式",
          "slug": "数据交换方式"
        },
        {
          "level": 3,
          "title": "网际协议IP",
          "slug": "网际协议ip"
        },
        {
          "level": 3,
          "title": "网际控制报文协议ICMP",
          "slug": "网际控制报文协议icmp"
        },
        {
          "level": 3,
          "title": "IPv6",
          "slug": "ipv6"
        },
        {
          "level": 3,
          "title": "路由选择协议",
          "slug": "路由选择协议"
        },
        {
          "level": 3,
          "title": "IP多播",
          "slug": "ip多播"
        },
        {
          "level": 3,
          "title": "移动IP",
          "slug": "移动ip"
        },
        {
          "level": 3,
          "title": "网络层设备",
          "slug": "网络层设备"
        },
        {
          "level": 2,
          "title": "第五章、运输层",
          "slug": "第五章、运输层"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 3,
          "title": "UDP协议",
          "slug": "udp协议"
        },
        {
          "level": 3,
          "title": "TCP协议",
          "slug": "tcp协议"
        },
        {
          "level": 2,
          "title": "第六章、应用层",
          "slug": "第六章、应用层"
        }
      ]
    },
    {
      "title": "操作系统",
      "frontmatter": {
        "title": "操作系统",
        "date": "2022-2-28",
        "sidebar": "auto",
        "tags": [
          "计算机基础",
          "操作系统"
        ],
        "categories": [
          "计算机基础"
        ]
      },
      "regularPath": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/",
      "relativePath": "blogs/计算机基础/operatingSystem/README.md",
      "key": "v-07ed4fc2",
      "path": "/blogs/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/operatingSystem/"
    },
    {
      "title": "emoji",
      "frontmatter": {
        "title": "emoji",
        "date": "2022-3-6",
        "subSidebar": false
      },
      "regularPath": "/other/emoji.html",
      "relativePath": "other/emoji.md",
      "key": "v-1918542e",
      "path": "/other/emoji.html",
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>常见的emoji大全</p>\n</div>"
    },
    {
      "title": "留言板",
      "frontmatter": {
        "title": "留言板",
        "date": "2022-2-28",
        "subSidebar": false
      },
      "regularPath": "/%E7%95%99%E8%A8%80%E6%9D%BF.html",
      "relativePath": "留言板.md",
      "key": "v-1c254a3c",
      "path": "/%E7%95%99%E8%A8%80%E6%9D%BF.html"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我",
        "date": "2022-3-1",
        "subSidebar": false,
        "keys": [
          "2d7cd5c74163fa45b5d7bdb458b7a5e4"
        ]
      },
      "regularPath": "/other/xiaoju.html",
      "relativePath": "other/xiaoju.md",
      "key": "v-1b3db930",
      "path": "/other/xiaoju.html"
    },
    {
      "title": "计划栏",
      "frontmatter": {
        "title": "计划栏",
        "date": "2022-2-28",
        "sticky": 1,
        "keys": [
          "2d7cd5c74163fa45b5d7bdb458b7a5e4"
        ]
      },
      "regularPath": "/%E8%AE%A1%E5%88%92%E6%A0%8F.html",
      "relativePath": "计划栏.md",
      "key": "v-1cd2fde4",
      "path": "/%E8%AE%A1%E5%88%92%E6%A0%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "重要事件",
          "slug": "重要事件"
        },
        {
          "level": 2,
          "title": "近日计划",
          "slug": "近日计划"
        },
        {
          "level": 3,
          "title": "⛅️上午",
          "slug": "上午"
        },
        {
          "level": 3,
          "title": "☀️下午",
          "slug": "下午"
        },
        {
          "level": 3,
          "title": "🌙晚上",
          "slug": "晚上"
        },
        {
          "level": 2,
          "title": "英语每日安排 📚",
          "slug": "英语每日安排"
        },
        {
          "level": 2,
          "title": "作息表 🌞",
          "slug": "作息表"
        },
        {
          "level": 2,
          "title": "蓝桥杯web考试范围",
          "slug": "蓝桥杯web考试范围"
        },
        {
          "level": 2,
          "title": "反省栏",
          "slug": "反省栏"
        },
        {
          "level": 2,
          "title": "往日计划",
          "slug": "往日计划"
        },
        {
          "level": 3,
          "title": "22/3/1",
          "slug": "_22-3-1"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>每个人的生命中，都有最艰难的一年，将人生变得美好而辽阔。🌸</p>\n</div>"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "后端 Tags"
      },
      "regularPath": "/tag/%E5%90%8E%E7%AB%AF/",
      "key": "v-47997495",
      "path": "/tag/后端/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Spring Tags"
      },
      "regularPath": "/tag/Spring/",
      "key": "v-4bb4ec90",
      "path": "/tag/Spring/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "SpringBoot Tags"
      },
      "regularPath": "/tag/SpringBoot/",
      "key": "v-54cc5f34",
      "path": "/tag/SpringBoot/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "框架 Tags"
      },
      "regularPath": "/tag/%E6%A1%86%E6%9E%B6/",
      "key": "v-1a384b6b",
      "path": "/tag/框架/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "MyBatis Tags"
      },
      "regularPath": "/tag/MyBatis/",
      "key": "v-f5f3b4b4",
      "path": "/tag/MyBatis/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "SpringMVC Tags"
      },
      "regularPath": "/tag/SpringMVC/",
      "key": "v-13372ce8",
      "path": "/tag/SpringMVC/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "算法 Tags"
      },
      "regularPath": "/tag/%E7%AE%97%E6%B3%95/",
      "key": "v-89abd2d6",
      "path": "/tag/算法/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "C语言 Tags"
      },
      "regularPath": "/tag/C%E8%AF%AD%E8%A8%80/",
      "key": "v-eb5eaa9a",
      "path": "/tag/C语言/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "数据结构 Tags"
      },
      "regularPath": "/tag/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/",
      "key": "v-92b3076c",
      "path": "/tag/数据结构/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "计算机基础 Tags"
      },
      "regularPath": "/tag/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/",
      "key": "v-d4fd937a",
      "path": "/tag/计算机基础/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "计算机组成原理 Tags"
      },
      "regularPath": "/tag/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BB%84%E6%88%90%E5%8E%9F%E7%90%86/",
      "key": "v-4cb5e150",
      "path": "/tag/计算机组成原理/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "计算机网络 Tags"
      },
      "regularPath": "/tag/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/",
      "key": "v-0aea8d27",
      "path": "/tag/计算机网络/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "操作系统 Tags"
      },
      "regularPath": "/tag/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/",
      "key": "v-9860895a",
      "path": "/tag/操作系统/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "后端 Categories"
      },
      "regularPath": "/categories/%E5%90%8E%E7%AB%AF/",
      "key": "v-12afc5a1",
      "path": "/categories/后端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "算法 Categories"
      },
      "regularPath": "/categories/%E7%AE%97%E6%B3%95/",
      "key": "v-f37f30be",
      "path": "/categories/算法/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "计算机基础 Categories"
      },
      "regularPath": "/categories/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/",
      "key": "v-0c66c492",
      "path": "/categories/计算机基础/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "嗨！好久不见",
        "tagline": "小橘不颂兮",
        "bgImage": "/assets/img/bg/晚霞.jpg",
        "bgImageStyle": {},
        "isShowTitleInHome": false,
        "features": [
          {
            "title": "Yesterday",
            "details": "逝者如斯"
          },
          {
            "title": "Today",
            "details": "活于此刻"
          },
          {
            "title": "Tomorrow",
            "details": "孤独前行"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-a96c5e80",
      "path": "/"
    },
    {
      "title": "CSS学习笔记",
      "frontmatter": {
        "title": "CSS学习笔记",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "css"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/blogs/CSS/CSS.html",
      "relativePath": "blogs/CSS/CSS.md",
      "key": "v-31e220a1",
      "path": "/blogs/CSS/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "1.视口",
          "slug": "_1-视口"
        },
        {
          "level": 3,
          "title": "meta视口标签",
          "slug": "meta视口标签"
        },
        {
          "level": 3,
          "title": "标准的viewport设置",
          "slug": "标准的viewport设置"
        },
        {
          "level": 2,
          "title": "2.二倍图",
          "slug": "_2-二倍图"
        },
        {
          "level": 3,
          "title": "2.1\t物理像素&物理像素比",
          "slug": "_2-1物理像素-物理像素比"
        },
        {
          "level": 3,
          "title": "2.2\t多倍图",
          "slug": "_2-2多倍图"
        },
        {
          "level": 3,
          "title": "2.3\t背景缩放 background-size",
          "slug": "_2-3背景缩放-background-size"
        },
        {
          "level": 2,
          "title": "3.\t移动端技术解决方案",
          "slug": "_3-移动端技术解决方案"
        },
        {
          "level": 3,
          "title": "3.1\t移动端浏览器",
          "slug": "_3-1移动端浏览器"
        },
        {
          "level": 3,
          "title": "3.2\tCSS初始化 normalize.css",
          "slug": "_3-2css初始化-normalize-css"
        },
        {
          "level": 3,
          "title": "3.3\tCSS3 盒子模型 box-sizing",
          "slug": "_3-3css3-盒子模型-box-sizing"
        },
        {
          "level": 3,
          "title": "3.4\t特殊样式",
          "slug": "_3-4特殊样式"
        },
        {
          "level": 2,
          "title": "4.\t2D转换",
          "slug": "_4-2d转换"
        },
        {
          "level": 3,
          "title": "4.1\t2D转换之移动 translate",
          "slug": "_4-12d转换之移动-translate"
        },
        {
          "level": 3,
          "title": "4.2\t2D转换之旋转 rotate",
          "slug": "_4-22d转换之旋转-rotate"
        },
        {
          "level": 3,
          "title": "4.3\t2D转换中心点 transform-origin",
          "slug": "_4-32d转换中心点-transform-origin"
        },
        {
          "level": 3,
          "title": "4.4\t2D转换之缩放\t scale",
          "slug": "_4-42d转换之缩放-scale"
        },
        {
          "level": 2,
          "title": "5. \t动画",
          "slug": "_5-动画"
        },
        {
          "level": 3,
          "title": "简写属性",
          "slug": "简写属性"
        },
        {
          "level": 3,
          "title": "速度曲线细节",
          "slug": "速度曲线细节"
        },
        {
          "level": 2,
          "title": "6.\t3D转换",
          "slug": "_6-3d转换"
        },
        {
          "level": 3,
          "title": "透视",
          "slug": "透视"
        },
        {
          "level": 3,
          "title": "3D旋转\trotate3d",
          "slug": "_3d旋转rotate3d"
        },
        {
          "level": 3,
          "title": "3D呈现 transfrom-style",
          "slug": "_3d呈现-transfrom-style"
        },
        {
          "level": 2,
          "title": "移动web开发",
          "slug": "移动web开发"
        },
        {
          "level": 3,
          "title": "rem基础",
          "slug": "rem基础"
        },
        {
          "level": 3,
          "title": "媒体查询",
          "slug": "媒体查询"
        },
        {
          "level": 3,
          "title": "Less基础",
          "slug": "less基础"
        },
        {
          "level": 3,
          "title": "rem适配方案",
          "slug": "rem适配方案"
        },
        {
          "level": 2,
          "title": "Bootstarp使用",
          "slug": "bootstarp使用"
        },
        {
          "level": 3,
          "title": "布局容器",
          "slug": "布局容器"
        },
        {
          "level": 3,
          "title": "栅格布局",
          "slug": "栅格布局"
        },
        {
          "level": 3,
          "title": "响应式工具",
          "slug": "响应式工具"
        }
      ]
    },
    {
      "title": "Bootstrap学习笔记",
      "frontmatter": {
        "title": "Bootstrap学习笔记",
        "date": "2022-03-20T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "css",
          "Bootstrap"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/blogs/CSS/Bootstrap.html",
      "relativePath": "blogs/CSS/Bootstrap.md",
      "key": "v-1c88f1c1",
      "path": "/blogs/CSS/Bootstrap.html",
      "headers": [
        {
          "level": 2,
          "title": "快速上手",
          "slug": "快速上手"
        },
        {
          "level": 2,
          "title": "栅格布局",
          "slug": "栅格布局"
        },
        {
          "level": 3,
          "title": "基础格式",
          "slug": "基础格式"
        },
        {
          "level": 3,
          "title": "栅格选项",
          "slug": "栅格选项"
        },
        {
          "level": 3,
          "title": "可变宽度的弹性空间",
          "slug": "可变宽度的弹性空间"
        },
        {
          "level": 3,
          "title": "等宽多行",
          "slug": "等宽多行"
        },
        {
          "level": 3,
          "title": "覆盖所有设备",
          "slug": "覆盖所有设备"
        },
        {
          "level": 3,
          "title": "沟槽 (★ 没太懂)",
          "slug": "沟槽-★-没太懂"
        },
        {
          "level": 3,
          "title": "行列布局",
          "slug": "行列布局"
        },
        {
          "level": 3,
          "title": "垂直对齐",
          "slug": "垂直对齐"
        },
        {
          "level": 3,
          "title": "水平对齐",
          "slug": "水平对齐"
        },
        {
          "level": 3,
          "title": "间隙沟槽(gutters)清除",
          "slug": "间隙沟槽-gutters-清除"
        },
        {
          "level": 3,
          "title": "换行",
          "slug": "换行"
        },
        {
          "level": 3,
          "title": "重排序",
          "slug": "重排序"
        },
        {
          "level": 3,
          "title": "列嵌套",
          "slug": "列嵌套"
        }
      ]
    },
    {
      "title": "ES6-11新特性",
      "frontmatter": {
        "title": "ES6-11新特性",
        "date": "2022-04-05T00:00:00.000Z",
        "tags": [
          "JavaScript",
          "前端"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/ES6-11%E6%96%B0%E7%89%B9%E6%80%A7.html",
      "relativePath": "blogs/JavaScript/ES6-11新特性.md",
      "key": "v-a75f35e6",
      "path": "/blogs/JavaScript/ES6-11%E6%96%B0%E7%89%B9%E6%80%A7.html",
      "headers": [
        {
          "level": 2,
          "title": "生成器函数",
          "slug": "生成器函数"
        },
        {
          "level": 3,
          "title": "声明方式",
          "slug": "声明方式"
        },
        {
          "level": 3,
          "title": "传递参数",
          "slug": "传递参数"
        },
        {
          "level": 3,
          "title": "在异步编程中的运用实例",
          "slug": "在异步编程中的运用实例"
        },
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 3,
          "title": "使用Promise封装AJAX",
          "slug": "使用promise封装ajax"
        },
        {
          "level": 3,
          "title": "then()方法",
          "slug": "then-方法"
        },
        {
          "level": 3,
          "title": "catch方法",
          "slug": "catch方法"
        },
        {
          "level": 2,
          "title": "class类",
          "slug": "class类"
        },
        {
          "level": 3,
          "title": "构造方法constructor()",
          "slug": "构造方法constructor"
        },
        {
          "level": 3,
          "title": "static 方法",
          "slug": "static-方法"
        },
        {
          "level": 3,
          "title": "getter和setter",
          "slug": "getter和setter"
        },
        {
          "level": 2,
          "title": "Object",
          "slug": "object"
        },
        {
          "level": 3,
          "title": "对象方法扩展",
          "slug": "对象方法扩展"
        },
        {
          "level": 2,
          "title": "模块化",
          "slug": "模块化"
        },
        {
          "level": 3,
          "title": "暴露的三种方式",
          "slug": "暴露的三种方式"
        },
        {
          "level": 3,
          "title": "引入方式",
          "slug": "引入方式"
        },
        {
          "level": 2,
          "title": "babel",
          "slug": "babel"
        },
        {
          "level": 3,
          "title": "安装工具",
          "slug": "安装工具"
        },
        {
          "level": 2,
          "title": "ES7",
          "slug": "es7"
        },
        {
          "level": 3,
          "title": "includes",
          "slug": "includes"
        },
        {
          "level": 3,
          "title": "**",
          "slug": ""
        },
        {
          "level": 2,
          "title": "ES8",
          "slug": "es8"
        },
        {
          "level": 3,
          "title": "async 函数",
          "slug": "async-函数"
        },
        {
          "level": 3,
          "title": "await函数",
          "slug": "await函数"
        },
        {
          "level": 3,
          "title": "对象拓展",
          "slug": "对象拓展"
        },
        {
          "level": 2,
          "title": "ES9",
          "slug": "es9"
        },
        {
          "level": 3,
          "title": "...运算符",
          "slug": "运算符"
        },
        {
          "level": 3,
          "title": "正则扩展运算符",
          "slug": "正则扩展运算符"
        },
        {
          "level": 2,
          "title": "ES10",
          "slug": "es10"
        },
        {
          "level": 3,
          "title": "Object.fromEntries()",
          "slug": "object-fromentries"
        },
        {
          "level": 3,
          "title": "trimStart 和 trimEnd",
          "slug": "trimstart-和-trimend"
        },
        {
          "level": 3,
          "title": "flat 和  flatMap",
          "slug": "flat-和-flatmap"
        },
        {
          "level": 3,
          "title": "Symbol.prototype.description()",
          "slug": "symbol-prototype-description"
        },
        {
          "level": 2,
          "title": "ES11",
          "slug": "es11"
        },
        {
          "level": 3,
          "title": "私有属性",
          "slug": "私有属性"
        },
        {
          "level": 3,
          "title": "Promise.allsettled()",
          "slug": "promise-allsettled"
        },
        {
          "level": 3,
          "title": "matchAll()",
          "slug": "matchall"
        },
        {
          "level": 3,
          "title": "?. 可选链操作符",
          "slug": "可选链操作符"
        },
        {
          "level": 3,
          "title": "动态 import",
          "slug": "动态-import"
        },
        {
          "level": 3,
          "title": "BigInt类型",
          "slug": "bigint类型"
        },
        {
          "level": 3,
          "title": "globalThis",
          "slug": "globalthis"
        }
      ]
    },
    {
      "title": "正则表达式",
      "frontmatter": {
        "title": "正则表达式",
        "date": "2021-10-28T00:00:00.000Z",
        "tags": [
          "JS",
          "正则表达式"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/RegularExpression.html",
      "relativePath": "blogs/JavaScript/RegularExpression.md",
      "key": "v-a6bf4572",
      "path": "/blogs/JavaScript/RegularExpression.html",
      "headers": [
        {
          "level": 2,
          "title": "基础",
          "slug": "基础"
        },
        {
          "level": 2,
          "title": "进阶",
          "slug": "进阶"
        },
        {
          "level": 3,
          "title": "分组",
          "slug": "分组"
        },
        {
          "level": 3,
          "title": "或者条件",
          "slug": "或者条件"
        },
        {
          "level": 3,
          "title": "非捕获分组",
          "slug": "非捕获分组"
        },
        {
          "level": 3,
          "title": "分组的回溯引用",
          "slug": "分组的回溯引用"
        },
        {
          "level": 2,
          "title": "规则",
          "slug": "规则"
        }
      ]
    },
    {
      "title": "函数小记",
      "frontmatter": {
        "title": "函数小记",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "C语言",
          "算法",
          "函数"
        ],
        "categories": [
          "C语言"
        ]
      },
      "regularPath": "/blogs/C%E8%AF%AD%E8%A8%80/%E5%87%BD%E6%95%B0%E5%B0%8F%E8%AE%B0.html",
      "relativePath": "blogs/C语言/函数小记.md",
      "key": "v-bbb94484",
      "path": "/blogs/C%E8%AF%AD%E8%A8%80/%E5%87%BD%E6%95%B0%E5%B0%8F%E8%AE%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "函数篇",
          "slug": "函数篇"
        },
        {
          "level": 2,
          "title": "memcpy",
          "slug": "memcpy"
        },
        {
          "level": 2,
          "title": "sprintf",
          "slug": "sprintf"
        },
        {
          "level": 2,
          "title": "snprintf",
          "slug": "snprintf"
        },
        {
          "level": 2,
          "title": "qsort",
          "slug": "qsort"
        },
        {
          "level": 2,
          "title": "memset",
          "slug": "memset"
        },
        {
          "level": 2,
          "title": "strpbrk",
          "slug": "strpbrk"
        },
        {
          "level": 2,
          "title": "strtok",
          "slug": "strtok"
        },
        {
          "level": 2,
          "title": "calloc",
          "slug": "calloc"
        },
        {
          "level": 2,
          "title": "strcat",
          "slug": "strcat"
        },
        {
          "level": 2,
          "title": "isalpha",
          "slug": "isalpha"
        },
        {
          "level": 2,
          "title": "tolower",
          "slug": "tolower"
        },
        {
          "level": 2,
          "title": "strdup",
          "slug": "strdup"
        },
        {
          "level": 2,
          "title": "strndup",
          "slug": "strndup"
        },
        {
          "level": 2,
          "title": "assert",
          "slug": "assert"
        },
        {
          "level": 2,
          "title": "算法篇",
          "slug": "算法篇"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>随力扣刷题，所见函数，记录于此</p>\n</div>"
    },
    {
      "title": "JS问题汇总",
      "frontmatter": {
        "title": "JS问题汇总",
        "date": "2022-03-23T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/JS%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB.html",
      "relativePath": "blogs/JavaScript/JS问题汇总.md",
      "key": "v-bf5d100e",
      "path": "/blogs/JavaScript/JS%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "使用原生JS在指定元素之前添加元素",
          "slug": "使用原生js在指定元素之前添加元素"
        },
        {
          "level": 2,
          "title": "使用原生JS 添加 / 删除 类",
          "slug": "使用原生js-添加-删除-类"
        }
      ]
    },
    {
      "title": "ES6模块化",
      "frontmatter": {
        "title": "ES6模块化",
        "date": "2022-3-06",
        "tags": [
          "ES6",
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/ES6%E6%A8%A1%E5%9D%97%E5%8C%96.html",
      "relativePath": "blogs/JavaScript/ES6模块化.md",
      "key": "v-e19918a6",
      "path": "/blogs/JavaScript/ES6%E6%A8%A1%E5%9D%97%E5%8C%96.html",
      "headers": [
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 3,
          "title": "导出",
          "slug": "导出"
        },
        {
          "level": 3,
          "title": "导入",
          "slug": "导入"
        },
        {
          "level": 3,
          "title": "直接导入并执行模块中的代码",
          "slug": "直接导入并执行模块中的代码"
        },
        {
          "level": 3,
          "title": "按需导入和按需导出的注意事项",
          "slug": "按需导入和按需导出的注意事项"
        },
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 3,
          "title": "基本概念",
          "slug": "基本概念"
        },
        {
          "level": 3,
          "title": "基于then-fs读取文件内容",
          "slug": "基于then-fs读取文件内容"
        },
        {
          "level": 3,
          "title": "then-fs的基本使用",
          "slug": "then-fs的基本使用"
        },
        {
          "level": 3,
          "title": "通过.catch方法捕获错误",
          "slug": "通过-catch方法捕获错误"
        },
        {
          "level": 3,
          "title": "Promise.all() 方法",
          "slug": "promise-all-方法"
        },
        {
          "level": 3,
          "title": "Promise.race() 方法",
          "slug": "promise-race-方法"
        },
        {
          "level": 3,
          "title": "基于Promise封装读文件的方法",
          "slug": "基于promise封装读文件的方法"
        },
        {
          "level": 2,
          "title": "async/await",
          "slug": "async-await"
        },
        {
          "level": 3,
          "title": "基本概念",
          "slug": "基本概念-2"
        },
        {
          "level": 2,
          "title": "EventLoop",
          "slug": "eventloop"
        },
        {
          "level": 2,
          "title": "宏任务和微任务",
          "slug": "宏任务和微任务"
        },
        {
          "level": 3,
          "title": "宏任务和微任务执行顺序",
          "slug": "宏任务和微任务执行顺序"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>配置基于node.js的ES6的模块化语法步骤</p>\n<ol>\n<li>node.js的版本要高于v14.15.1</li>\n<li>在package.json的根节点中添加<code>“type“:module””</code></li>\n</ol>\n</div>"
    },
    {
      "title": "WebAPI",
      "frontmatter": {
        "title": "WebAPI",
        "date": "2021-10-28T00:00:00.000Z",
        "tags": [
          "JS",
          "DOM",
          "BOM"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/WebAPI.html",
      "relativePath": "blogs/JavaScript/WebAPI.md",
      "key": "v-3bd931fb",
      "path": "/blogs/JavaScript/WebAPI.html",
      "headers": [
        {
          "level": 2,
          "title": "1.事件",
          "slug": "_1-事件"
        },
        {
          "level": 2,
          "title": "三种创建元素的区别",
          "slug": "三种创建元素的区别"
        },
        {
          "level": 3,
          "title": "改",
          "slug": "改"
        },
        {
          "level": 3,
          "title": "查",
          "slug": "查"
        },
        {
          "level": 2,
          "title": "注册事件",
          "slug": "注册事件"
        },
        {
          "level": 3,
          "title": "DOM事件流",
          "slug": "dom事件流"
        },
        {
          "level": 3,
          "title": "事件对象常见的属性和方法",
          "slug": "事件对象常见的属性和方法"
        },
        {
          "level": 3,
          "title": "事件委托",
          "slug": "事件委托"
        },
        {
          "level": 3,
          "title": "鼠标事件",
          "slug": "鼠标事件"
        },
        {
          "level": 3,
          "title": "鼠标事件对象",
          "slug": "鼠标事件对象"
        },
        {
          "level": 3,
          "title": "键盘事件",
          "slug": "键盘事件"
        },
        {
          "level": 3,
          "title": "窗口加载事件",
          "slug": "窗口加载事件"
        },
        {
          "level": 3,
          "title": "调整窗口大小事件",
          "slug": "调整窗口大小事件"
        },
        {
          "level": 3,
          "title": "定时器",
          "slug": "定时器"
        },
        {
          "level": 2,
          "title": "同步和异步",
          "slug": "同步和异步"
        },
        {
          "level": 3,
          "title": "执行机制",
          "slug": "执行机制"
        },
        {
          "level": 3,
          "title": "location",
          "slug": "location"
        },
        {
          "level": 2,
          "title": "元素偏移",
          "slug": "元素偏移"
        },
        {
          "level": 3,
          "title": "offset",
          "slug": "offset"
        },
        {
          "level": 3,
          "title": "client",
          "slug": "client"
        },
        {
          "level": 3,
          "title": "scroll",
          "slug": "scroll"
        },
        {
          "level": 3,
          "title": "三大系列对比",
          "slug": "三大系列对比"
        },
        {
          "level": 3,
          "title": "mouseenter 和 mouseover的区别",
          "slug": "mouseenter-和-mouseover的区别"
        },
        {
          "level": 2,
          "title": "触屏事件",
          "slug": "触屏事件"
        },
        {
          "level": 3,
          "title": "触摸事件对象",
          "slug": "触摸事件对象"
        },
        {
          "level": 3,
          "title": "classList",
          "slug": "classlist"
        },
        {
          "level": 3,
          "title": "click事件延时问题解决",
          "slug": "click事件延时问题解决"
        },
        {
          "level": 2,
          "title": "本地存储",
          "slug": "本地存储"
        },
        {
          "level": 3,
          "title": "window.sessionStorage",
          "slug": "window-sessionstorage"
        },
        {
          "level": 3,
          "title": "window.localStorage",
          "slug": "window-localstorage"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>有关js原生DOM和BOM的知识点</p>\n</div>"
    },
    {
      "title": "选择器",
      "frontmatter": {
        "title": "选择器",
        "date": "2022-3-06",
        "tags": [
          "css",
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/%E9%80%89%E6%8B%A9%E5%99%A8.html",
      "relativePath": "blogs/JavaScript/选择器.md",
      "key": "v-3469717d",
      "path": "/blogs/JavaScript/%E9%80%89%E6%8B%A9%E5%99%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "js原生选择器",
          "slug": "js原生选择器"
        },
        {
          "level": 3,
          "title": "getElementById(ID)",
          "slug": "getelementbyid-id"
        },
        {
          "level": 3,
          "title": "getElementByTagName(TagName)",
          "slug": "getelementbytagname-tagname"
        },
        {
          "level": 3,
          "title": "getElementByClassName()",
          "slug": "getelementbyclassname"
        },
        {
          "level": 3,
          "title": "querySelector()",
          "slug": "queryselector"
        },
        {
          "level": 3,
          "title": "querySelectAll()",
          "slug": "queryselectall"
        },
        {
          "level": 2,
          "title": "jQuery选择器",
          "slug": "jquery选择器"
        },
        {
          "level": 2,
          "title": "CSS选择器",
          "slug": "css选择器"
        }
      ]
    },
    {
      "title": "项目配置",
      "frontmatter": {
        "title": "项目配置",
        "date": "2022-4-5",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/Vue/%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE.html",
      "relativePath": "blogs/Vue/项目配置.md",
      "key": "v-0b039106",
      "path": "/blogs/Vue/%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue-cil",
          "slug": "vue-cil"
        },
        {
          "level": 2,
          "title": "webpack",
          "slug": "webpack"
        },
        {
          "level": 3,
          "title": "webpack其他插件",
          "slug": "webpack其他插件"
        },
        {
          "level": 2,
          "title": "package.json",
          "slug": "package-json"
        },
        {
          "level": 2,
          "title": "jQuery",
          "slug": "jquery"
        },
        {
          "level": 2,
          "title": "nodemon",
          "slug": "nodemon"
        },
        {
          "level": 2,
          "title": "day.js",
          "slug": "day-js"
        },
        {
          "level": 2,
          "title": "axios",
          "slug": "axios"
        },
        {
          "level": 3,
          "title": "vue-aioxs",
          "slug": "vue-aioxs"
        },
        {
          "level": 2,
          "title": "vue-router",
          "slug": "vue-router"
        },
        {
          "level": 2,
          "title": "vant",
          "slug": "vant"
        },
        {
          "level": 2,
          "title": "vue-calendar-component——基于 vue 2.0 开发的轻量，高性能日历组件",
          "slug": "vue-calendar-component-基于-vue-2-0-开发的轻量-高性能日历组件"
        },
        {
          "level": 2,
          "title": "qs： 是一个增加了一些安全性的查询字符串解析和序列化字符串的库。",
          "slug": "qs-是一个增加了一些安全性的查询字符串解析和序列化字符串的库。"
        },
        {
          "level": 2,
          "title": "vue-cropper：基于vue的图片上传切图工具",
          "slug": "vue-cropper-基于vue的图片上传切图工具"
        }
      ]
    },
    {
      "title": "jQuery",
      "frontmatter": {
        "title": "jQuery",
        "date": "2021-10-28T00:00:00.000Z",
        "tags": [
          "JS",
          "jQuery"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/blogs/JavaScript/jQuery.html",
      "relativePath": "blogs/JavaScript/jQuery.md",
      "key": "v-b3a5960a",
      "path": "/blogs/JavaScript/jQuery.html",
      "headers": [
        {
          "level": 2,
          "title": "概念",
          "slug": "概念"
        },
        {
          "level": 2,
          "title": "优点",
          "slug": "优点"
        },
        {
          "level": 2,
          "title": "入口函数",
          "slug": "入口函数"
        },
        {
          "level": 2,
          "title": "顶级对象\t\t$",
          "slug": "顶级对象"
        },
        {
          "level": 2,
          "title": "jQuery对象和DOM原生对象",
          "slug": "jquery对象和dom原生对象"
        },
        {
          "level": 3,
          "title": "jQuery对象和DOM原生对象相互转换",
          "slug": "jquery对象和dom原生对象相互转换"
        },
        {
          "level": 2,
          "title": "jQuery 选择器",
          "slug": "jquery-选择器"
        },
        {
          "level": 3,
          "title": "jQuery 基础选择器",
          "slug": "jquery-基础选择器"
        },
        {
          "level": 3,
          "title": "jQuery 层级选择器",
          "slug": "jquery-层级选择器"
        },
        {
          "level": 3,
          "title": "jQuery 筛选选择器",
          "slug": "jquery-筛选选择器"
        },
        {
          "level": 3,
          "title": "筛选方法",
          "slug": "筛选方法"
        },
        {
          "level": 3,
          "title": "隐式迭代",
          "slug": "隐式迭代"
        },
        {
          "level": 2,
          "title": "样式操作",
          "slug": "样式操作"
        },
        {
          "level": 3,
          "title": "操作CSS方法",
          "slug": "操作css方法"
        },
        {
          "level": 3,
          "title": "操作类方法",
          "slug": "操作类方法"
        },
        {
          "level": 3,
          "title": "类操作与className的区别",
          "slug": "类操作与classname的区别"
        },
        {
          "level": 2,
          "title": "jQuery效果",
          "slug": "jquery效果"
        },
        {
          "level": 3,
          "title": "显示隐藏效果",
          "slug": "显示隐藏效果"
        },
        {
          "level": 3,
          "title": "事件切换",
          "slug": "事件切换"
        },
        {
          "level": 3,
          "title": "淡入淡出效果",
          "slug": "淡入淡出效果"
        },
        {
          "level": 3,
          "title": "自定义动画animate",
          "slug": "自定义动画animate"
        },
        {
          "level": 2,
          "title": "jQuery属性操作",
          "slug": "jquery属性操作"
        },
        {
          "level": 3,
          "title": "设置固有属性值： prop()",
          "slug": "设置固有属性值-prop"
        },
        {
          "level": 3,
          "title": "设置或获取元素自定义属性值： attr()",
          "slug": "设置或获取元素自定义属性值-attr"
        },
        {
          "level": 2,
          "title": "jQuery元素操作",
          "slug": "jquery元素操作"
        },
        {
          "level": 3,
          "title": "遍历元素",
          "slug": "遍历元素"
        },
        {
          "level": 3,
          "title": "创建、添加、删除元素",
          "slug": "创建、添加、删除元素"
        },
        {
          "level": 2,
          "title": "jQuery事件",
          "slug": "jquery事件"
        },
        {
          "level": 3,
          "title": "事件绑定：on",
          "slug": "事件绑定-on"
        },
        {
          "level": 3,
          "title": "事件解绑：off()",
          "slug": "事件解绑-off"
        },
        {
          "level": 3,
          "title": "自动触发事件 : trigger()",
          "slug": "自动触发事件-trigger"
        },
        {
          "level": 2,
          "title": "事件对象",
          "slug": "事件对象"
        },
        {
          "level": 2,
          "title": "jQuery其他方法",
          "slug": "jquery其他方法"
        },
        {
          "level": 3,
          "title": "对象拷贝",
          "slug": "对象拷贝"
        },
        {
          "level": 3,
          "title": "多库共存",
          "slug": "多库共存"
        },
        {
          "level": 2,
          "title": "jQuery插件",
          "slug": "jquery插件"
        },
        {
          "level": 2,
          "title": "jQuery尺寸",
          "slug": "jquery尺寸"
        },
        {
          "level": 2,
          "title": "jQuery位置",
          "slug": "jquery位置"
        }
      ]
    },
    {
      "title": "Vue2.x学习笔记",
      "frontmatter": {
        "title": "Vue2.x学习笔记",
        "date": "2022-3-06",
        "tags": [
          "Vue"
        ],
        "categories": [
          "Vue"
        ]
      },
      "regularPath": "/blogs/Vue/Vue.html",
      "relativePath": "blogs/Vue/Vue.md",
      "key": "v-26481be1",
      "path": "/blogs/Vue/Vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue项目的搭建",
          "slug": "vue项目的搭建"
        },
        {
          "level": 2,
          "title": "项目结构",
          "slug": "项目结构"
        },
        {
          "level": 2,
          "title": "MVVM（Model View ViewModel）",
          "slug": "mvvm-model-view-viewmodel"
        },
        {
          "level": 2,
          "title": "$event",
          "slug": "event"
        },
        {
          "level": 2,
          "title": "事件修饰符",
          "slug": "事件修饰符"
        },
        {
          "level": 2,
          "title": "v-for",
          "slug": "v-for"
        },
        {
          "level": 2,
          "title": "v-model",
          "slug": "v-model"
        },
        {
          "level": 3,
          "title": "修饰符",
          "slug": "修饰符"
        },
        {
          "level": 2,
          "title": "v-key",
          "slug": "v-key"
        },
        {
          "level": 2,
          "title": "过滤器",
          "slug": "过滤器"
        },
        {
          "level": 2,
          "title": "侦听器",
          "slug": "侦听器"
        },
        {
          "level": 2,
          "title": "计算属性",
          "slug": "计算属性"
        },
        {
          "level": 2,
          "title": "axios",
          "slug": "axios"
        },
        {
          "level": 3,
          "title": "axios 的基本使用",
          "slug": "axios-的基本使用"
        },
        {
          "level": 2,
          "title": "组件化",
          "slug": "组件化"
        },
        {
          "level": 2,
          "title": "组件传值",
          "slug": "组件传值"
        },
        {
          "level": 3,
          "title": "父传子",
          "slug": "父传子"
        },
        {
          "level": 3,
          "title": "子传父",
          "slug": "子传父"
        },
        {
          "level": 3,
          "title": "兄弟互传",
          "slug": "兄弟互传"
        },
        {
          "level": 2,
          "title": "ref引用",
          "slug": "ref引用"
        },
        {
          "level": 3,
          "title": "this.$nextTick(cb) 方法",
          "slug": "this-nexttick-cb-方法"
        },
        {
          "level": 2,
          "title": "插槽",
          "slug": "插槽"
        },
        {
          "level": 3,
          "title": "具名插槽",
          "slug": "具名插槽"
        },
        {
          "level": 3,
          "title": "作用域插槽",
          "slug": "作用域插槽"
        },
        {
          "level": 2,
          "title": "生命周期",
          "slug": "生命周期"
        },
        {
          "level": 2,
          "title": "Vuex",
          "slug": "vuex"
        },
        {
          "level": 3,
          "title": "State单一状态树(Single Source of Truth)",
          "slug": "state单一状态树-single-source-of-truth"
        },
        {
          "level": 3,
          "title": "Getters",
          "slug": "getters"
        },
        {
          "level": 3,
          "title": "Mutation状态更新",
          "slug": "mutation状态更新"
        },
        {
          "level": 3,
          "title": "Action（异步操作）",
          "slug": "action-异步操作"
        },
        {
          "level": 2,
          "title": "自定义指令",
          "slug": "自定义指令"
        },
        {
          "level": 3,
          "title": "私有自定义指令",
          "slug": "私有自定义指令"
        },
        {
          "level": 3,
          "title": "全局自定义指令",
          "slug": "全局自定义指令"
        },
        {
          "level": 2,
          "title": "axios配置",
          "slug": "axios配置"
        },
        {
          "level": 2,
          "title": "前端路由",
          "slug": "前端路由"
        },
        {
          "level": 3,
          "title": "vue-router的安装和配置步骤",
          "slug": "vue-router的安装和配置步骤"
        },
        {
          "level": 3,
          "title": "路由重定向",
          "slug": "路由重定向"
        },
        {
          "level": 3,
          "title": "嵌套路由",
          "slug": "嵌套路由"
        },
        {
          "level": 3,
          "title": "动态路由",
          "slug": "动态路由"
        },
        {
          "level": 3,
          "title": "query和fullPath",
          "slug": "query和fullpath"
        },
        {
          "level": 3,
          "title": "编程式导航",
          "slug": "编程式导航"
        },
        {
          "level": 3,
          "title": "导航守卫",
          "slug": "导航守卫"
        },
        {
          "level": 2,
          "title": "Storage封装",
          "slug": "storage封装"
        },
        {
          "level": 2,
          "title": "接口代理",
          "slug": "接口代理"
        },
        {
          "level": 2,
          "title": "注意事项",
          "slug": "注意事项"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>Vue学习笔记，从<code>创建项目</code>到<code>项目开发</code></p>\n</div>"
    },
    {
      "title": "Nginx",
      "frontmatter": {
        "title": "Nginx",
        "date": "2022-04-01T00:00:00.000Z",
        "tags": [
          "Nginx",
          "前端"
        ],
        "categories": [
          "前端"
        ]
      },
      "regularPath": "/blogs/%E5%89%8D%E7%AB%AF/Nginx.html",
      "relativePath": "blogs/前端/Nginx.md",
      "key": "v-0ed12090",
      "path": "/blogs/%E5%89%8D%E7%AB%AF/Nginx.html",
      "headers": [
        {
          "level": 2,
          "title": "Nginx反向代理配置",
          "slug": "nginx反向代理配置"
        },
        {
          "level": 2,
          "title": "启动",
          "slug": "启动"
        }
      ]
    },
    {
      "title": "vuepress-theme-reco",
      "frontmatter": {
        "title": "vuepress-theme-reco",
        "date": "2019-04-09T00:00:00.000Z"
      },
      "regularPath": "/blogs/other/guide.html",
      "relativePath": "blogs/other/guide.md",
      "key": "v-6e055221",
      "path": "/blogs/other/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Use",
          "slug": "use"
        },
        {
          "level": 2,
          "title": "Play Together",
          "slug": "play-together"
        },
        {
          "level": 3,
          "title": "0.x",
          "slug": "_0-x"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 3,
          "title": "CLI",
          "slug": "cli"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ]
    },
    {
      "title": "在Vue中使用vue-cropper裁剪图片并向nodejs后台传入数据",
      "frontmatter": {
        "title": "在Vue中使用vue-cropper裁剪图片并向nodejs后台传入数据",
        "date": "2022-04-06T00:00:00.000Z",
        "tags": [
          "Node",
          "Vue",
          "前端"
        ],
        "categories": [
          "前端"
        ]
      },
      "regularPath": "/blogs/%E5%89%8D%E7%AB%AF/%E5%9C%A8Vue%E4%B8%AD%E4%BD%BF%E7%94%A8vue-cropper%E8%A3%81%E5%89%AA%E5%9B%BE%E7%89%87%E5%B9%B6%E5%90%91nodejs%E5%90%8E%E5%8F%B0%E4%BC%A0%E5%85%A5%E6%95%B0%E6%8D%AE.html",
      "relativePath": "blogs/前端/在Vue中使用vue-cropper裁剪图片并向nodejs后台传入数据.md",
      "key": "v-1487c8af",
      "path": "/blogs/%E5%89%8D%E7%AB%AF/%E5%9C%A8Vue%E4%B8%AD%E4%BD%BF%E7%94%A8vue-cropper%E8%A3%81%E5%89%AA%E5%9B%BE%E7%89%87%E5%B9%B6%E5%90%91nodejs%E5%90%8E%E5%8F%B0%E4%BC%A0%E5%85%A5%E6%95%B0%E6%8D%AE.html",
      "headers": [
        {
          "level": 2,
          "title": "在Vue项目中引入Vue-cropper",
          "slug": "在vue项目中引入vue-cropper"
        },
        {
          "level": 3,
          "title": "封装组件CropperImage.vue",
          "slug": "封装组件cropperimage-vue"
        },
        {
          "level": 3,
          "title": "新建Tailoring.vue",
          "slug": "新建tailoring-vue"
        },
        {
          "level": 2,
          "title": "向后端传值",
          "slug": "向后端传值"
        },
        {
          "level": 2,
          "title": "后端接收",
          "slug": "后端接收"
        },
        {
          "level": 3,
          "title": "安装解析表单数据插件",
          "slug": "安装解析表单数据插件"
        },
        {
          "level": 3,
          "title": "处理数据",
          "slug": "处理数据"
        },
        {
          "level": 3,
          "title": "修改文件路径",
          "slug": "修改文件路径"
        },
        {
          "level": 2,
          "title": "额外收获",
          "slug": "额外收获"
        },
        {
          "level": 3,
          "title": "Nodejs复制文件的四种方法",
          "slug": "nodejs复制文件的四种方法"
        },
        {
          "level": 3,
          "title": "copyFile",
          "slug": "copyfile"
        },
        {
          "level": 3,
          "title": "readFile、writeFile",
          "slug": "readfile、writefile"
        },
        {
          "level": 3,
          "title": "createReadStream、read、write",
          "slug": "createreadstream、read、write"
        },
        {
          "level": 3,
          "title": "pipe",
          "slug": "pipe"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "webpack",
      "frontmatter": {
        "title": "webpack",
        "date": "2022-03-26T00:00:00.000Z",
        "tags": [
          "JS",
          "前端"
        ],
        "categories": [
          "前端"
        ]
      },
      "regularPath": "/blogs/%E5%89%8D%E7%AB%AF/webpack.html",
      "relativePath": "blogs/前端/webpack.md",
      "key": "v-c31ff5dc",
      "path": "/blogs/%E5%89%8D%E7%AB%AF/webpack.html",
      "headers": [
        {
          "level": 2,
          "title": "五个核心概念",
          "slug": "五个核心概念"
        },
        {
          "level": 3,
          "title": "1. Entry",
          "slug": "_1-entry"
        },
        {
          "level": 3,
          "title": "2.Output",
          "slug": "_2-output"
        },
        {
          "level": 3,
          "title": "3. Loader",
          "slug": "_3-loader"
        },
        {
          "level": 3,
          "title": "4. Plugins",
          "slug": "_4-plugins"
        },
        {
          "level": 3,
          "title": "5. Mode",
          "slug": "_5-mode"
        },
        {
          "level": 2,
          "title": "webpack使用",
          "slug": "webpack使用"
        },
        {
          "level": 2,
          "title": "打包",
          "slug": "打包"
        },
        {
          "level": 3,
          "title": "css",
          "slug": "css"
        },
        {
          "level": 3,
          "title": "Less",
          "slug": "less"
        },
        {
          "level": 3,
          "title": "HTML",
          "slug": "html"
        },
        {
          "level": 3,
          "title": "图片",
          "slug": "图片"
        },
        {
          "level": 3,
          "title": "其他资源",
          "slug": "其他资源"
        },
        {
          "level": 3,
          "title": "devServer",
          "slug": "devserver"
        },
        {
          "level": 2,
          "title": "开发环境",
          "slug": "开发环境"
        },
        {
          "level": 2,
          "title": "处理",
          "slug": "处理"
        },
        {
          "level": 3,
          "title": "提取css文件",
          "slug": "提取css文件"
        },
        {
          "level": 3,
          "title": "css兼容性处理",
          "slug": "css兼容性处理"
        },
        {
          "level": 3,
          "title": "压缩CSS",
          "slug": "压缩css"
        },
        {
          "level": 3,
          "title": "eslint",
          "slug": "eslint"
        },
        {
          "level": 3,
          "title": "js兼容性",
          "slug": "js兼容性"
        },
        {
          "level": 3,
          "title": "js压缩",
          "slug": "js压缩"
        },
        {
          "level": 3,
          "title": "html压缩",
          "slug": "html压缩"
        },
        {
          "level": 2,
          "title": "生产环境",
          "slug": "生产环境"
        },
        {
          "level": 2,
          "title": "优化配置",
          "slug": "优化配置"
        },
        {
          "level": 3,
          "title": "开发环境性能优化",
          "slug": "开发环境性能优化"
        },
        {
          "level": 3,
          "title": "生产环境性能优化",
          "slug": "生产环境性能优化"
        },
        {
          "level": 3,
          "title": "HMK",
          "slug": "hmk"
        },
        {
          "level": 3,
          "title": "source-map",
          "slug": "source-map"
        },
        {
          "level": 3,
          "title": "oneOf",
          "slug": "oneof"
        },
        {
          "level": 3,
          "title": "缓存",
          "slug": "缓存"
        },
        {
          "level": 3,
          "title": "tree shaking",
          "slug": "tree-shaking"
        },
        {
          "level": 3,
          "title": "代码分割",
          "slug": "代码分割"
        },
        {
          "level": 3,
          "title": "PWA",
          "slug": "pwa"
        },
        {
          "level": 3,
          "title": "多线程打包",
          "slug": "多线程打包"
        },
        {
          "level": 3,
          "title": "externals",
          "slug": "externals"
        },
        {
          "level": 3,
          "title": "dll",
          "slug": "dll"
        }
      ]
    },
    {
      "title": "学习问题汇总",
      "frontmatter": {
        "title": "学习问题汇总",
        "date": "2022-03-26T00:00:00.000Z",
        "tags": [
          "Vue",
          "CSS",
          "JS",
          "JavaScript",
          "前端"
        ],
        "categories": [
          "前端"
        ]
      },
      "regularPath": "/blogs/%E5%89%8D%E7%AB%AF/%E5%AD%A6%E4%B9%A0%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB.html",
      "relativePath": "blogs/前端/学习问题汇总.md",
      "key": "v-0f370447",
      "path": "/blogs/%E5%89%8D%E7%AB%AF/%E5%AD%A6%E4%B9%A0%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "vue相关",
          "slug": "vue相关"
        },
        {
          "level": 2,
          "title": "CSS相关样式",
          "slug": "css相关样式"
        }
      ]
    },
    {
      "title": "Spring",
      "frontmatter": {
        "title": "Spring",
        "date": "2021-10-28T00:00:00.000Z",
        "sidebar": "auto",
        "tags": [
          "后端",
          "Spring",
          "框架"
        ],
        "categories": [
          "后端"
        ]
      },
      "regularPath": "/blogs/%E5%90%8E%E7%AB%AF/Spring.html",
      "relativePath": "blogs/后端/Spring.md",
      "key": "v-d1f4fd2c",
      "path": "/blogs/%E5%90%8E%E7%AB%AF/Spring.html",
      "headers": [
        {
          "level": 2,
          "title": "1、Spring创建",
          "slug": "_1、spring创建"
        },
        {
          "level": 2,
          "title": "2、项目基础",
          "slug": "_2、项目基础"
        },
        {
          "level": 3,
          "title": "自动注解",
          "slug": "自动注解"
        },
        {
          "level": 3,
          "title": "多配置文件",
          "slug": "多配置文件"
        },
        {
          "level": 3,
          "title": "注解",
          "slug": "注解"
        },
        {
          "level": 2,
          "title": "3、动态代理",
          "slug": "_3、动态代理"
        },
        {
          "level": 3,
          "title": "动态代理的作用",
          "slug": "动态代理的作用"
        },
        {
          "level": 3,
          "title": "Aop（Aspect Oriented Programming）",
          "slug": "aop-aspect-oriented-programming"
        },
        {
          "level": 3,
          "title": "aop的实现",
          "slug": "aop的实现"
        },
        {
          "level": 3,
          "title": "JoinPoint",
          "slug": "joinpoint"
        },
        {
          "level": 2,
          "title": "4、spring和mybatis",
          "slug": "_4、spring和mybatis"
        },
        {
          "level": 3,
          "title": "mybatis使用",
          "slug": "mybatis使用"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 2,
          "title": "5、spring事务",
          "slug": "_5、spring事务"
        },
        {
          "level": 3,
          "title": "步骤",
          "slug": "步骤"
        },
        {
          "level": 3,
          "title": "使用spring事务注解管理事务",
          "slug": "使用spring事务注解管理事务"
        }
      ]
    },
    {
      "title": "Node.js",
      "frontmatter": {
        "title": "Node.js",
        "date": "2022-03-26T00:00:00.000Z",
        "tags": [
          "JS",
          "Node",
          "前端"
        ],
        "categories": [
          "前端"
        ]
      },
      "regularPath": "/blogs/%E5%89%8D%E7%AB%AF/Node.js.html",
      "relativePath": "blogs/前端/Node.js.md",
      "key": "v-59d718c2",
      "path": "/blogs/%E5%89%8D%E7%AB%AF/Node.js.html",
      "headers": [
        {
          "level": 2,
          "title": "fs文件系统模块",
          "slug": "fs文件系统模块"
        },
        {
          "level": 2,
          "title": "http 模块",
          "slug": "http-模块"
        },
        {
          "level": 3,
          "title": "创建web服务器的基本步骤",
          "slug": "创建web服务器的基本步骤"
        },
        {
          "level": 3,
          "title": "Res.end()",
          "slug": "res-end"
        },
        {
          "level": 3,
          "title": "根据不同的url响应不同的html内容",
          "slug": "根据不同的url响应不同的html内容"
        },
        {
          "level": 2,
          "title": "模块化",
          "slug": "模块化"
        },
        {
          "level": 3,
          "title": "module.exports",
          "slug": "module-exports"
        },
        {
          "level": 3,
          "title": "module.exports和exports使用误区",
          "slug": "module-exports和exports使用误区"
        },
        {
          "level": 2,
          "title": "Express",
          "slug": "express"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "创建基本的web服务器",
          "slug": "创建基本的web服务器"
        },
        {
          "level": 3,
          "title": "Express基本使用",
          "slug": "express基本使用"
        },
        {
          "level": 3,
          "title": "托管静态资源",
          "slug": "托管静态资源"
        },
        {
          "level": 3,
          "title": "nodemon热更新",
          "slug": "nodemon热更新"
        },
        {
          "level": 3,
          "title": "Express路由",
          "slug": "express路由"
        },
        {
          "level": 2,
          "title": "中间件",
          "slug": "中间件"
        },
        {
          "level": 3,
          "title": "注册全局中间件",
          "slug": "注册全局中间件"
        },
        {
          "level": 3,
          "title": "局部中间件",
          "slug": "局部中间件"
        },
        {
          "level": 3,
          "title": "注意事项",
          "slug": "注意事项"
        },
        {
          "level": 3,
          "title": "中间件的分类",
          "slug": "中间件的分类"
        },
        {
          "level": 2,
          "title": "跨域",
          "slug": "跨域"
        },
        {
          "level": 3,
          "title": "使用CORS中间件",
          "slug": "使用cors中间件"
        },
        {
          "level": 3,
          "title": "CORS响应头",
          "slug": "cors响应头"
        },
        {
          "level": 3,
          "title": "CORS请求分类",
          "slug": "cors请求分类"
        },
        {
          "level": 2,
          "title": "操作数据库",
          "slug": "操作数据库"
        },
        {
          "level": 3,
          "title": "安装与配置",
          "slug": "安装与配置"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 3,
          "title": "增",
          "slug": "增"
        },
        {
          "level": 3,
          "title": "改",
          "slug": "改"
        },
        {
          "level": 3,
          "title": "删",
          "slug": "删"
        },
        {
          "level": 2,
          "title": "Session认证",
          "slug": "session认证"
        },
        {
          "level": 3,
          "title": "安装express-session",
          "slug": "安装express-session"
        },
        {
          "level": 3,
          "title": "配置 express-session 中间件",
          "slug": "配置-express-session-中间件"
        },
        {
          "level": 3,
          "title": "向 session 中存数据",
          "slug": "向-session-中存数据"
        },
        {
          "level": 2,
          "title": "JWT 认证",
          "slug": "jwt-认证"
        },
        {
          "level": 3,
          "title": "在 Express 中 使用 JWT",
          "slug": "在-express-中-使用-jwt"
        },
        {
          "level": 2,
          "title": "数据验证",
          "slug": "数据验证"
        }
      ]
    },
    {
      "title": "vuepress构建步骤",
      "frontmatter": {
        "title": "vuepress构建步骤",
        "date": "2022-3-1",
        "sticky": 2,
        "tags": [
          "vuepress"
        ],
        "categories": [
          "前端"
        ]
      },
      "regularPath": "/blogs/%E5%89%8D%E7%AB%AF/vuepress.html",
      "relativePath": "blogs/前端/vuepress.md",
      "key": "v-35f1eb34",
      "path": "/blogs/%E5%89%8D%E7%AB%AF/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "准备工作",
          "slug": "准备工作"
        },
        {
          "level": 2,
          "title": "在github中新建项目",
          "slug": "在github中新建项目"
        },
        {
          "level": 2,
          "title": "构建项目",
          "slug": "构建项目"
        },
        {
          "level": 2,
          "title": "基本配置",
          "slug": "基本配置"
        },
        {
          "level": 3,
          "title": "配置config.js",
          "slug": "配置config-js"
        },
        {
          "level": 3,
          "title": "配置导航栏以及侧边栏",
          "slug": "配置导航栏以及侧边栏"
        },
        {
          "level": 2,
          "title": "更新时间",
          "slug": "更新时间"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用-2"
        },
        {
          "level": 3,
          "title": "选项",
          "slug": "选项"
        },
        {
          "level": 2,
          "title": "发布",
          "slug": "发布"
        },
        {
          "level": 3,
          "title": "创建deploy.sh",
          "slug": "创建deploy-sh"
        },
        {
          "level": 3,
          "title": "Github Pages部署",
          "slug": "github-pages部署"
        },
        {
          "level": 2,
          "title": "配置PWA",
          "slug": "配置pwa"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装-2"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用-3"
        },
        {
          "level": 2,
          "title": "vssue评论",
          "slug": "vssue评论"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装-3"
        },
        {
          "level": 3,
          "title": "使用插件",
          "slug": "使用插件"
        },
        {
          "level": 3,
          "title": "clientId和clientSecret 生成",
          "slug": "clientid和clientsecret-生成"
        },
        {
          "level": 3,
          "title": "使用 Vssue 组件",
          "slug": "使用-vssue-组件"
        },
        {
          "level": 3,
          "title": "全局配置Vssue",
          "slug": "全局配置vssue"
        },
        {
          "level": 2,
          "title": "back-to-top",
          "slug": "back-to-top"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装-4"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用-4"
        },
        {
          "level": 2,
          "title": "图片缩放",
          "slug": "图片缩放"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装-5"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用-5"
        },
        {
          "level": 2,
          "title": "Github Actions自动部署",
          "slug": "github-actions自动部署"
        },
        {
          "level": 3,
          "title": "创建deploy.yml",
          "slug": "创建deploy-yml"
        },
        {
          "level": 3,
          "title": "生成令牌",
          "slug": "生成令牌"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>想搭建一个属于自己的博客吗？这里应该有你需要的</p>\n</div>"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "css Tags"
      },
      "regularPath": "/tag/css/",
      "key": "v-323b9794",
      "path": "/tag/css/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Bootstrap Tags"
      },
      "regularPath": "/tag/Bootstrap/",
      "key": "v-40d0e9cb",
      "path": "/tag/Bootstrap/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaScript Tags"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "前端 Tags"
      },
      "regularPath": "/tag/%E5%89%8D%E7%AB%AF/",
      "key": "v-49a56e2a",
      "path": "/tag/前端/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JS Tags"
      },
      "regularPath": "/tag/JS/",
      "key": "v-e8d965c8",
      "path": "/tag/JS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "正则表达式 Tags"
      },
      "regularPath": "/tag/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F/",
      "key": "v-a4358e00",
      "path": "/tag/正则表达式/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "函数 Tags"
      },
      "regularPath": "/tag/%E5%87%BD%E6%95%B0/",
      "key": "v-5c9b2e55",
      "path": "/tag/函数/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ES6 Tags"
      },
      "regularPath": "/tag/ES6/",
      "key": "v-3257dcde",
      "path": "/tag/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "DOM Tags"
      },
      "regularPath": "/tag/DOM/",
      "key": "v-3258de12",
      "path": "/tag/DOM/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "BOM Tags"
      },
      "regularPath": "/tag/BOM/",
      "key": "v-325aaf8e",
      "path": "/tag/BOM/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vue Tags"
      },
      "regularPath": "/tag/Vue/",
      "key": "v-32475d9a",
      "path": "/tag/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "jQuery Tags"
      },
      "regularPath": "/tag/jQuery/",
      "key": "v-66172787",
      "path": "/tag/jQuery/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Nginx Tags"
      },
      "regularPath": "/tag/Nginx/",
      "key": "v-dab8e1c2",
      "path": "/tag/Nginx/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Node Tags"
      },
      "regularPath": "/tag/Node/",
      "key": "v-178b3c3a",
      "path": "/tag/Node/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CSS Tags"
      },
      "regularPath": "/tag/CSS/",
      "key": "v-3259a754",
      "path": "/tag/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vuepress Tags"
      },
      "regularPath": "/tag/vuepress/",
      "key": "v-dfb71430",
      "path": "/tag/vuepress/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "CSS Categories"
      },
      "regularPath": "/categories/CSS/",
      "key": "v-7efe64ca",
      "path": "/categories/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "JavaScript Categories"
      },
      "regularPath": "/categories/JavaScript/",
      "key": "v-081e6844",
      "path": "/categories/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "C语言 Categories"
      },
      "regularPath": "/categories/C%E8%AF%AD%E8%A8%80/",
      "key": "v-22047b27",
      "path": "/categories/C语言/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Vue Categories"
      },
      "regularPath": "/categories/Vue/",
      "key": "v-7f0789a7",
      "path": "/categories/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "计划栏",
        "icon": "reco-document",
        "link": "/计划栏"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "工具箱",
        "icon": "iconfont icon-gongju",
        "items": [
          {
            "text": "兼容性查询（前端必备）",
            "link": "https://caniuse.com"
          },
          {
            "text": "API请求测试",
            "link": "https://httpbin.org/"
          },
          {
            "text": "在线PS",
            "link": "https://ps.gaoding.com/#/"
          },
          {
            "text": "在线一键抠图",
            "link": "https://www.remove.bg/zh"
          },
          {
            "text": "API请求测试",
            "link": "https://snippet-generator.app/"
          },
          {
            "text": "Lks推荐网站合集（实用）",
            "link": "https://xiangjianan.gitee.io/lks/"
          },
          {
            "text": "壁纸站",
            "link": "https://wallhaven.cc/"
          },
          {
            "text": "CSS渐变色",
            "link": "https://color.oulu.me/"
          },
          {
            "text": "前端样式平台",
            "link": "https://codepen.io/?cursor=ZD0xJm89MCZwPTEmdj02Njc4OA=="
          },
          {
            "text": "在线JSON校验",
            "link": "https://www.bejson.com/"
          },
          {
            "text": "格式转换工具——convertio",
            "link": "https://convertio.co/zh/"
          },
          {
            "text": "格式转换工具——aconvert",
            "link": "https://www.aconvert.com/cn/"
          },
          {
            "text": "中国传统颜色",
            "link": "http://zhongguose.com/"
          },
          {
            "text": "千亿像素看中国",
            "link": "http://www.bigpixel.cn/"
          },
          {
            "text": "文档搜索引擎",
            "link": "https://www.jiumodiary.com/"
          },
          {
            "text": "在线字体（前端可用）",
            "link": "https://www.webfont.com/"
          },
          {
            "text": "艺术字体库",
            "link": "http://www.diyiziti.com/"
          }
        ]
      },
      {
        "text": "留言板",
        "icon": "reco-message",
        "link": "/留言板"
      },
      {
        "text": "其他",
        "icon": "reco-message",
        "items": [
          {
            "text": "emoji",
            "link": "/other/emoji",
            "icon": "reco-account"
          }
        ]
      },
      {
        "text": "关于",
        "icon": "reco-message",
        "items": [
          {
            "text": "关于我",
            "link": "/other/xiaoju",
            "icon": "reco-account"
          },
          {
            "text": "GitHub",
            "link": "https://github.com/recoluan",
            "icon": "reco-github"
          },
          {
            "text": "CSDN",
            "link": "https://www.csdn.net/",
            "icon": "reco-csdn"
          },
          {
            "text": "LeanCloud",
            "link": "https://console.leancloud.cn/apps",
            "icon": "iconfont icon-gongju"
          }
        ]
      }
    ],
    "valineConfig": {
      "appId": "DXFkz6H4Ht7b9lXaJfBdR5sv-gzGzoHsz",
      "appKey": "5hqYKCfaazHurBbjUU2sAP1Y"
    },
    "subSidebar": "auto",
    "sidebar": {
      "/blogs/计算机基础/": [
        "compositionPrinciple/",
        "computerNetwork/",
        "dataStructure/",
        "operatingSystem/"
      ],
      "/blogs/CSS/": [
        "CSS",
        "Bootstrap"
      ],
      "/blogs/JavaScript/": [
        "jQuery",
        "RegularExpression",
        "WebAPI",
        "ES6模块化",
        "选择器",
        "JS问题汇总",
        "ES6-11新特性"
      ],
      "/blogs/Vue/": [
        "Vue",
        "项目配置"
      ],
      "/blogs/前端/": [
        "Node.js",
        "Nginx",
        "vuepress",
        "webpack",
        "学习问题汇总",
        "在Vue中使用vue-cropper裁剪图片并向nodejs后台传入数据"
      ],
      "/blogs/后端/": [
        "MyBatis",
        "Spring",
        "SpringBoot",
        "SpringMVC"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [],
    "logo": "/小橘.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "更新时间",
    "author": "小橘不颂兮",
    "authorAvatar": "/assets/img/avatar/mmexport1639710400520.jpg",
    "record": "xxxx",
    "startYear": "2022 "
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}