/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "css": {
      "key": "css",
      "scope": "tags",
      "path": "/tag/css/",
      "pageKeys": [
        "v-31e220a1"
      ]
    },
    "C语言": {
      "key": "C语言",
      "scope": "tags",
      "path": "/tag/C语言/",
      "pageKeys": [
        "v-bbb94484",
        "v-9c20d530"
      ]
    },
    "算法": {
      "key": "算法",
      "scope": "tags",
      "path": "/tag/算法/",
      "pageKeys": [
        "v-bbb94484",
        "v-9c20d530"
      ]
    },
    "函数": {
      "key": "函数",
      "scope": "tags",
      "path": "/tag/函数/",
      "pageKeys": [
        "v-bbb94484"
      ]
    },
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-3bd931fb",
        "v-a6bf4572",
        "v-b3a5960a"
      ]
    },
    "DOM": {
      "key": "DOM",
      "scope": "tags",
      "path": "/tag/DOM/",
      "pageKeys": [
        "v-3bd931fb"
      ]
    },
    "BOM": {
      "key": "BOM",
      "scope": "tags",
      "path": "/tag/BOM/",
      "pageKeys": [
        "v-3bd931fb"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tag/ES6/",
      "pageKeys": [
        "v-e19918a6"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-e19918a6"
      ]
    },
    "正则表达式": {
      "key": "正则表达式",
      "scope": "tags",
      "path": "/tag/正则表达式/",
      "pageKeys": [
        "v-a6bf4572"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "tags",
      "path": "/tag/Vue/",
      "pageKeys": [
        "v-26481be1"
      ]
    },
    "框架": {
      "key": "框架",
      "scope": "tags",
      "path": "/tag/框架/",
      "pageKeys": [
        "v-26481be1",
        "v-34c608b2",
        "v-d1f4fd2c",
        "v-4b6b7dfe",
        "v-dfa392ac"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "tags",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-bc6631ca"
      ]
    },
    "后端": {
      "key": "后端",
      "scope": "tags",
      "path": "/tag/后端/",
      "pageKeys": [
        "v-34c608b2",
        "v-d1f4fd2c",
        "v-4b6b7dfe",
        "v-dfa392ac"
      ]
    },
    "MyBatis": {
      "key": "MyBatis",
      "scope": "tags",
      "path": "/tag/MyBatis/",
      "pageKeys": [
        "v-34c608b2"
      ]
    },
    "Spring": {
      "key": "Spring",
      "scope": "tags",
      "path": "/tag/Spring/",
      "pageKeys": [
        "v-d1f4fd2c",
        "v-4b6b7dfe",
        "v-dfa392ac"
      ]
    },
    "SpringMVC": {
      "key": "SpringMVC",
      "scope": "tags",
      "path": "/tag/SpringMVC/",
      "pageKeys": [
        "v-4b6b7dfe"
      ]
    },
    "jQuery": {
      "key": "jQuery",
      "scope": "tags",
      "path": "/tag/jQuery/",
      "pageKeys": [
        "v-b3a5960a"
      ]
    },
    "数据结构": {
      "key": "数据结构",
      "scope": "tags",
      "path": "/tag/数据结构/",
      "pageKeys": [
        "v-9c20d530",
        "v-575e9ced"
      ]
    },
    "SpringBoot": {
      "key": "SpringBoot",
      "scope": "tags",
      "path": "/tag/SpringBoot/",
      "pageKeys": [
        "v-dfa392ac"
      ]
    },
    "计算机基础": {
      "key": "计算机基础",
      "scope": "tags",
      "path": "/tag/计算机基础/",
      "pageKeys": [
        "v-1f9f56c9",
        "v-07ed4fc2",
        "v-583e6a99",
        "v-575e9ced"
      ]
    },
    "计算机组成原理": {
      "key": "计算机组成原理",
      "scope": "tags",
      "path": "/tag/计算机组成原理/",
      "pageKeys": [
        "v-1f9f56c9"
      ]
    },
    "操作系统": {
      "key": "操作系统",
      "scope": "tags",
      "path": "/tag/操作系统/",
      "pageKeys": [
        "v-07ed4fc2"
      ]
    },
    "计算机网络": {
      "key": "计算机网络",
      "scope": "tags",
      "path": "/tag/计算机网络/",
      "pageKeys": [
        "v-583e6a99"
      ]
    }
  },
  "categories": {
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-31e220a1"
      ]
    },
    "C语言": {
      "key": "C语言",
      "scope": "categories",
      "path": "/categories/C语言/",
      "pageKeys": [
        "v-bbb94484"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-3bd931fb",
        "v-e19918a6",
        "v-a6bf4572",
        "v-b3a5960a"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-26481be1"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "categories",
      "path": "/categories/vuepress/",
      "pageKeys": [
        "v-bc6631ca"
      ]
    },
    "后端": {
      "key": "后端",
      "scope": "categories",
      "path": "/categories/后端/",
      "pageKeys": [
        "v-34c608b2",
        "v-d1f4fd2c",
        "v-4b6b7dfe",
        "v-dfa392ac"
      ]
    },
    "算法": {
      "key": "算法",
      "scope": "categories",
      "path": "/categories/算法/",
      "pageKeys": [
        "v-9c20d530"
      ]
    },
    "计算机基础": {
      "key": "计算机基础",
      "scope": "categories",
      "path": "/categories/计算机基础/",
      "pageKeys": [
        "v-1f9f56c9",
        "v-07ed4fc2",
        "v-583e6a99",
        "v-575e9ced"
      ]
    }
  },
  "timeline": {}
}